package sampada.pojo;
// Generated Jan 19, 2021 2:14:19 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * AdjMapping generated by hbm2java
 */
public class AdjMapping  implements java.io.Serializable {


     private BigDecimal slNo;
     private Corporates corporates;
     private DisbursedInterestDetails disbursedInterestDetails;
     private InterestDetails interestDetails;
     private BillPayableCorp billPayableCorpByPayId;
     private BillPayableCorp billPayableCorpByPayRefId;
     private BillReceiveCorp billReceiveCorpByRecvId;
     private BillReceiveCorp billReceiveCorpByRecRefId;
     private AdjPayment adjPayment;
     private String corpName;
     private BigDecimal payBal;
     private BigDecimal recBal;
     private BigDecimal payRefBal;
     private BigDecimal recRefBal;
     private BigDecimal payIntBal;
     private BigDecimal recIntBal;
     private String status;
     private BigDecimal adjustAmt;

    public AdjMapping() {
    }

	
    public AdjMapping(BigDecimal slNo) {
        this.slNo = slNo;
    }
    public AdjMapping(BigDecimal slNo, Corporates corporates, DisbursedInterestDetails disbursedInterestDetails, InterestDetails interestDetails, BillPayableCorp billPayableCorpByPayId, BillPayableCorp billPayableCorpByPayRefId, BillReceiveCorp billReceiveCorpByRecvId, BillReceiveCorp billReceiveCorpByRecRefId, AdjPayment adjPayment, String corpName, BigDecimal payBal, BigDecimal recBal, BigDecimal payRefBal, BigDecimal recRefBal, BigDecimal payIntBal, BigDecimal recIntBal, String status, BigDecimal adjustAmt) {
       this.slNo = slNo;
       this.corporates = corporates;
       this.disbursedInterestDetails = disbursedInterestDetails;
       this.interestDetails = interestDetails;
       this.billPayableCorpByPayId = billPayableCorpByPayId;
       this.billPayableCorpByPayRefId = billPayableCorpByPayRefId;
       this.billReceiveCorpByRecvId = billReceiveCorpByRecvId;
       this.billReceiveCorpByRecRefId = billReceiveCorpByRecRefId;
       this.adjPayment = adjPayment;
       this.corpName = corpName;
       this.payBal = payBal;
       this.recBal = recBal;
       this.payRefBal = payRefBal;
       this.recRefBal = recRefBal;
       this.payIntBal = payIntBal;
       this.recIntBal = recIntBal;
       this.status = status;
       this.adjustAmt = adjustAmt;
    }
   
    public BigDecimal getSlNo() {
        return this.slNo;
    }
    
    public void setSlNo(BigDecimal slNo) {
        this.slNo = slNo;
    }
    public Corporates getCorporates() {
        return this.corporates;
    }
    
    public void setCorporates(Corporates corporates) {
        this.corporates = corporates;
    }
    public DisbursedInterestDetails getDisbursedInterestDetails() {
        return this.disbursedInterestDetails;
    }
    
    public void setDisbursedInterestDetails(DisbursedInterestDetails disbursedInterestDetails) {
        this.disbursedInterestDetails = disbursedInterestDetails;
    }
    public InterestDetails getInterestDetails() {
        return this.interestDetails;
    }
    
    public void setInterestDetails(InterestDetails interestDetails) {
        this.interestDetails = interestDetails;
    }
    public BillPayableCorp getBillPayableCorpByPayId() {
        return this.billPayableCorpByPayId;
    }
    
    public void setBillPayableCorpByPayId(BillPayableCorp billPayableCorpByPayId) {
        this.billPayableCorpByPayId = billPayableCorpByPayId;
    }
    public BillPayableCorp getBillPayableCorpByPayRefId() {
        return this.billPayableCorpByPayRefId;
    }
    
    public void setBillPayableCorpByPayRefId(BillPayableCorp billPayableCorpByPayRefId) {
        this.billPayableCorpByPayRefId = billPayableCorpByPayRefId;
    }
    public BillReceiveCorp getBillReceiveCorpByRecvId() {
        return this.billReceiveCorpByRecvId;
    }
    
    public void setBillReceiveCorpByRecvId(BillReceiveCorp billReceiveCorpByRecvId) {
        this.billReceiveCorpByRecvId = billReceiveCorpByRecvId;
    }
    public BillReceiveCorp getBillReceiveCorpByRecRefId() {
        return this.billReceiveCorpByRecRefId;
    }
    
    public void setBillReceiveCorpByRecRefId(BillReceiveCorp billReceiveCorpByRecRefId) {
        this.billReceiveCorpByRecRefId = billReceiveCorpByRecRefId;
    }
    public AdjPayment getAdjPayment() {
        return this.adjPayment;
    }
    
    public void setAdjPayment(AdjPayment adjPayment) {
        this.adjPayment = adjPayment;
    }
    public String getCorpName() {
        return this.corpName;
    }
    
    public void setCorpName(String corpName) {
        this.corpName = corpName;
    }
    public BigDecimal getPayBal() {
        return this.payBal;
    }
    
    public void setPayBal(BigDecimal payBal) {
        this.payBal = payBal;
    }
    public BigDecimal getRecBal() {
        return this.recBal;
    }
    
    public void setRecBal(BigDecimal recBal) {
        this.recBal = recBal;
    }
    public BigDecimal getPayRefBal() {
        return this.payRefBal;
    }
    
    public void setPayRefBal(BigDecimal payRefBal) {
        this.payRefBal = payRefBal;
    }
    public BigDecimal getRecRefBal() {
        return this.recRefBal;
    }
    
    public void setRecRefBal(BigDecimal recRefBal) {
        this.recRefBal = recRefBal;
    }
    public BigDecimal getPayIntBal() {
        return this.payIntBal;
    }
    
    public void setPayIntBal(BigDecimal payIntBal) {
        this.payIntBal = payIntBal;
    }
    public BigDecimal getRecIntBal() {
        return this.recIntBal;
    }
    
    public void setRecIntBal(BigDecimal recIntBal) {
        this.recIntBal = recIntBal;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public BigDecimal getAdjustAmt() {
        return adjustAmt;
    }

    public void setAdjustAmt(BigDecimal adjustAmt) {
        this.adjustAmt = adjustAmt;
    }




}


