package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BankStatement generated by hbm2java
 */
public class BankStatement  implements java.io.Serializable {


     private BigDecimal stmtId;
     private Corporates corporates;
     private UserDetails userDetails;
     private Date stmtFromdate;
     private Date stmtTodate;
     private Date amountDate;
     private String amountTime;
     private BigDecimal paidAmount;
     private String receiptNumber;
     private String creditDebitFlag;
     private String transactionType;
     private BigDecimal openBalance;
     private BigDecimal mainBalance;
     private BigDecimal mappedAmount;
     private BigDecimal mappedBalance;
     private String mappedStatus;
     private String stmtStatus;
     private String remarks;
     private Date entryDate;
     private String entryDesc;
     private BigDecimal poolBal;
     private String reconFlag;
     private String disburseType;
     private BigDecimal disburseId;
     private Date entryTime;
     private Set tempMappingBillBanks = new HashSet(0);
     private Set mappingBillBanks = new HashSet(0);
     private Set tempMapBankStatements = new HashSet(0);
     private Set mappingInterestBanks = new HashSet(0);
     private Set mappingRefundBanks = new HashSet(0);

    public BankStatement() {
    }

	
    public BankStatement(BigDecimal stmtId) {
        this.stmtId = stmtId;
    }
    public BankStatement(BigDecimal stmtId, Corporates corporates, UserDetails userDetails, Date stmtFromdate, Date stmtTodate, Date amountDate, String amountTime, BigDecimal paidAmount, String receiptNumber, String creditDebitFlag, String transactionType, BigDecimal openBalance, BigDecimal mainBalance, BigDecimal mappedAmount, BigDecimal mappedBalance, String mappedStatus, String stmtStatus, String remarks, Date entryDate, String entryDesc, BigDecimal poolBal, String reconFlag, String disburseType, BigDecimal disburseId, Date entryTime, Set tempMappingBillBanks, Set mappingBillBanks, Set tempMapBankStatements, Set mappingInterestBanks, Set mappingRefundBanks) {
       this.stmtId = stmtId;
       this.corporates = corporates;
       this.userDetails = userDetails;
       this.stmtFromdate = stmtFromdate;
       this.stmtTodate = stmtTodate;
       this.amountDate = amountDate;
       this.amountTime = amountTime;
       this.paidAmount = paidAmount;
       this.receiptNumber = receiptNumber;
       this.creditDebitFlag = creditDebitFlag;
       this.transactionType = transactionType;
       this.openBalance = openBalance;
       this.mainBalance = mainBalance;
       this.mappedAmount = mappedAmount;
       this.mappedBalance = mappedBalance;
       this.mappedStatus = mappedStatus;
       this.stmtStatus = stmtStatus;
       this.remarks = remarks;
       this.entryDate = entryDate;
       this.entryDesc = entryDesc;
       this.poolBal = poolBal;
       this.reconFlag = reconFlag;
       this.disburseType = disburseType;
       this.disburseId = disburseId;
       this.entryTime = entryTime;
       this.tempMappingBillBanks = tempMappingBillBanks;
       this.mappingBillBanks = mappingBillBanks;
       this.tempMapBankStatements = tempMapBankStatements;
       this.mappingInterestBanks = mappingInterestBanks;
       this.mappingRefundBanks = mappingRefundBanks;
    }
   
    public BigDecimal getStmtId() {
        return this.stmtId;
    }
    
    public void setStmtId(BigDecimal stmtId) {
        this.stmtId = stmtId;
    }
    public Corporates getCorporates() {
        return this.corporates;
    }
    
    public void setCorporates(Corporates corporates) {
        this.corporates = corporates;
    }
    public UserDetails getUserDetails() {
        return this.userDetails;
    }
    
    public void setUserDetails(UserDetails userDetails) {
        this.userDetails = userDetails;
    }
    public Date getStmtFromdate() {
        return this.stmtFromdate;
    }
    
    public void setStmtFromdate(Date stmtFromdate) {
        this.stmtFromdate = stmtFromdate;
    }
    public Date getStmtTodate() {
        return this.stmtTodate;
    }
    
    public void setStmtTodate(Date stmtTodate) {
        this.stmtTodate = stmtTodate;
    }
    public Date getAmountDate() {
        return this.amountDate;
    }
    
    public void setAmountDate(Date amountDate) {
        this.amountDate = amountDate;
    }
    public String getAmountTime() {
        return this.amountTime;
    }
    
    public void setAmountTime(String amountTime) {
        this.amountTime = amountTime;
    }
    public BigDecimal getPaidAmount() {
        return this.paidAmount;
    }
    
    public void setPaidAmount(BigDecimal paidAmount) {
        this.paidAmount = paidAmount;
    }
    public String getReceiptNumber() {
        return this.receiptNumber;
    }
    
    public void setReceiptNumber(String receiptNumber) {
        this.receiptNumber = receiptNumber;
    }
    public String getCreditDebitFlag() {
        return this.creditDebitFlag;
    }
    
    public void setCreditDebitFlag(String creditDebitFlag) {
        this.creditDebitFlag = creditDebitFlag;
    }
    public String getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }
    public BigDecimal getOpenBalance() {
        return this.openBalance;
    }
    
    public void setOpenBalance(BigDecimal openBalance) {
        this.openBalance = openBalance;
    }
    public BigDecimal getMainBalance() {
        return this.mainBalance;
    }
    
    public void setMainBalance(BigDecimal mainBalance) {
        this.mainBalance = mainBalance;
    }
    public BigDecimal getMappedAmount() {
        return this.mappedAmount;
    }
    
    public void setMappedAmount(BigDecimal mappedAmount) {
        this.mappedAmount = mappedAmount;
    }
    public BigDecimal getMappedBalance() {
        return this.mappedBalance;
    }
    
    public void setMappedBalance(BigDecimal mappedBalance) {
        this.mappedBalance = mappedBalance;
    }
    public String getMappedStatus() {
        return this.mappedStatus;
    }
    
    public void setMappedStatus(String mappedStatus) {
        this.mappedStatus = mappedStatus;
    }
    public String getStmtStatus() {
        return this.stmtStatus;
    }
    
    public void setStmtStatus(String stmtStatus) {
        this.stmtStatus = stmtStatus;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
    public String getEntryDesc() {
        return this.entryDesc;
    }
    
    public void setEntryDesc(String entryDesc) {
        this.entryDesc = entryDesc;
    }
    public BigDecimal getPoolBal() {
        return this.poolBal;
    }
    
    public void setPoolBal(BigDecimal poolBal) {
        this.poolBal = poolBal;
    }
    public String getReconFlag() {
        return this.reconFlag;
    }
    
    public void setReconFlag(String reconFlag) {
        this.reconFlag = reconFlag;
    }
    public String getDisburseType() {
        return this.disburseType;
    }
    
    public void setDisburseType(String disburseType) {
        this.disburseType = disburseType;
    }
    public BigDecimal getDisburseId() {
        return this.disburseId;
    }
    
    public void setDisburseId(BigDecimal disburseId) {
        this.disburseId = disburseId;
    }
    public Date getEntryTime() {
        return this.entryTime;
    }
    
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }
    public Set getTempMappingBillBanks() {
        return this.tempMappingBillBanks;
    }
    
    public void setTempMappingBillBanks(Set tempMappingBillBanks) {
        this.tempMappingBillBanks = tempMappingBillBanks;
    }
    public Set getMappingBillBanks() {
        return this.mappingBillBanks;
    }
    
    public void setMappingBillBanks(Set mappingBillBanks) {
        this.mappingBillBanks = mappingBillBanks;
    }
    public Set getTempMapBankStatements() {
        return this.tempMapBankStatements;
    }
    
    public void setTempMapBankStatements(Set tempMapBankStatements) {
        this.tempMapBankStatements = tempMapBankStatements;
    }
    public Set getMappingInterestBanks() {
        return this.mappingInterestBanks;
    }
    
    public void setMappingInterestBanks(Set mappingInterestBanks) {
        this.mappingInterestBanks = mappingInterestBanks;
    }
    public Set getMappingRefundBanks() {
        return this.mappingRefundBanks;
    }
    
    public void setMappingRefundBanks(Set mappingRefundBanks) {
        this.mappingRefundBanks = mappingRefundBanks;
    }




}


