package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * BillInterestRate generated by hbm2java
 */
public class BillInterestRate  implements java.io.Serializable {


     private BigDecimal slno;
     private String billtype;
     private BigDecimal interestRate;
     private BigDecimal noofduedays;
     private String category;

    public BillInterestRate() {
    }

	
    public BillInterestRate(BigDecimal slno) {
        this.slno = slno;
    }
    public BillInterestRate(BigDecimal slno, String billtype, BigDecimal interestRate, BigDecimal noofduedays, String category) {
       this.slno = slno;
       this.billtype = billtype;
       this.interestRate = interestRate;
       this.noofduedays = noofduedays;
       this.category = category;
    }
   
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }
    public String getBilltype() {
        return this.billtype;
    }
    
    public void setBilltype(String billtype) {
        this.billtype = billtype;
    }
    public BigDecimal getInterestRate() {
        return this.interestRate;
    }
    
    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }
    public BigDecimal getNoofduedays() {
        return this.noofduedays;
    }
    
    public void setNoofduedays(BigDecimal noofduedays) {
        this.noofduedays = noofduedays;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }




}


