package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BillPayableCorp generated by hbm2java
 */
public class BillPayableCorp  implements java.io.Serializable {


     private BigDecimal uniqueId;
     private Corporates corporates;
     private BigDecimal weekId;
     private BigDecimal totalnet;
     private BigDecimal revisedrefund;
     private BigDecimal revisedpaybale;
     private Date billingDate;
     private BigDecimal billYear;
     private String billStatus;
     private Date billDueDate;
     private BigDecimal revisionNo;
     private String remarks;
     private String billType;
     private String billCategory;
     private String billPriority;
     private BigDecimal pendingAmount;
     private BigDecimal paidAmount;
     private String adjustmentFlag;
     private BigDecimal adjustmentAmount;
     private Set mappingBillBanks = new HashSet(0);
     private Set tempRefundBillCorps = new HashSet(0);
     private Set tempMappingBillBanks = new HashSet(0);
     private Set defaultLocDetailses = new HashSet(0);

    public BillPayableCorp() {
    }

	
    public BillPayableCorp(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }
    public BillPayableCorp(BigDecimal uniqueId, Corporates corporates, BigDecimal weekId, BigDecimal totalnet, BigDecimal revisedrefund, BigDecimal revisedpaybale, Date billingDate, BigDecimal billYear, String billStatus, Date billDueDate, BigDecimal revisionNo, String remarks, String billType, String billCategory, String billPriority, BigDecimal pendingAmount, BigDecimal paidAmount, String adjustmentFlag, BigDecimal adjustmentAmount, Set mappingBillBanks, Set tempRefundBillCorps, Set tempMappingBillBanks, Set defaultLocDetailses) {
       this.uniqueId = uniqueId;
       this.corporates = corporates;
       this.weekId = weekId;
       this.totalnet = totalnet;
       this.revisedrefund = revisedrefund;
       this.revisedpaybale = revisedpaybale;
       this.billingDate = billingDate;
       this.billYear = billYear;
       this.billStatus = billStatus;
       this.billDueDate = billDueDate;
       this.revisionNo = revisionNo;
       this.remarks = remarks;
       this.billType = billType;
       this.billCategory = billCategory;
       this.billPriority = billPriority;
       this.pendingAmount = pendingAmount;
       this.paidAmount = paidAmount;
       this.adjustmentFlag = adjustmentFlag;
       this.adjustmentAmount = adjustmentAmount;
       this.mappingBillBanks = mappingBillBanks;
       this.tempRefundBillCorps = tempRefundBillCorps;
       this.tempMappingBillBanks = tempMappingBillBanks;
       this.defaultLocDetailses = defaultLocDetailses;
    }
   
    public BigDecimal getUniqueId() {
        return this.uniqueId;
    }
    
    public void setUniqueId(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }
    public Corporates getCorporates() {
        return this.corporates;
    }
    
    public void setCorporates(Corporates corporates) {
        this.corporates = corporates;
    }
    public BigDecimal getWeekId() {
        return this.weekId;
    }
    
    public void setWeekId(BigDecimal weekId) {
        this.weekId = weekId;
    }
    public BigDecimal getTotalnet() {
        return this.totalnet;
    }
    
    public void setTotalnet(BigDecimal totalnet) {
        this.totalnet = totalnet;
    }
    public BigDecimal getRevisedrefund() {
        return this.revisedrefund;
    }
    
    public void setRevisedrefund(BigDecimal revisedrefund) {
        this.revisedrefund = revisedrefund;
    }
    public BigDecimal getRevisedpaybale() {
        return this.revisedpaybale;
    }
    
    public void setRevisedpaybale(BigDecimal revisedpaybale) {
        this.revisedpaybale = revisedpaybale;
    }
    public Date getBillingDate() {
        return this.billingDate;
    }
    
    public void setBillingDate(Date billingDate) {
        this.billingDate = billingDate;
    }
    public BigDecimal getBillYear() {
        return this.billYear;
    }
    
    public void setBillYear(BigDecimal billYear) {
        this.billYear = billYear;
    }
    public String getBillStatus() {
        return this.billStatus;
    }
    
    public void setBillStatus(String billStatus) {
        this.billStatus = billStatus;
    }
    public Date getBillDueDate() {
        return this.billDueDate;
    }
    
    public void setBillDueDate(Date billDueDate) {
        this.billDueDate = billDueDate;
    }
    public BigDecimal getRevisionNo() {
        return this.revisionNo;
    }
    
    public void setRevisionNo(BigDecimal revisionNo) {
        this.revisionNo = revisionNo;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getBillType() {
        return this.billType;
    }
    
    public void setBillType(String billType) {
        this.billType = billType;
    }
    public String getBillCategory() {
        return this.billCategory;
    }
    
    public void setBillCategory(String billCategory) {
        this.billCategory = billCategory;
    }
    public String getBillPriority() {
        return this.billPriority;
    }
    
    public void setBillPriority(String billPriority) {
        this.billPriority = billPriority;
    }
    public BigDecimal getPendingAmount() {
        return this.pendingAmount;
    }
    
    public void setPendingAmount(BigDecimal pendingAmount) {
        this.pendingAmount = pendingAmount;
    }
    public BigDecimal getPaidAmount() {
        return this.paidAmount;
    }
    
    public void setPaidAmount(BigDecimal paidAmount) {
        this.paidAmount = paidAmount;
    }
    public String getAdjustmentFlag() {
        return this.adjustmentFlag;
    }
    
    public void setAdjustmentFlag(String adjustmentFlag) {
        this.adjustmentFlag = adjustmentFlag;
    }
    public BigDecimal getAdjustmentAmount() {
        return this.adjustmentAmount;
    }
    
    public void setAdjustmentAmount(BigDecimal adjustmentAmount) {
        this.adjustmentAmount = adjustmentAmount;
    }
    public Set getMappingBillBanks() {
        return this.mappingBillBanks;
    }
    
    public void setMappingBillBanks(Set mappingBillBanks) {
        this.mappingBillBanks = mappingBillBanks;
    }
    public Set getTempRefundBillCorps() {
        return this.tempRefundBillCorps;
    }
    
    public void setTempRefundBillCorps(Set tempRefundBillCorps) {
        this.tempRefundBillCorps = tempRefundBillCorps;
    }
    public Set getTempMappingBillBanks() {
        return this.tempMappingBillBanks;
    }
    
    public void setTempMappingBillBanks(Set tempMappingBillBanks) {
        this.tempMappingBillBanks = tempMappingBillBanks;
    }
    public Set getDefaultLocDetailses() {
        return this.defaultLocDetailses;
    }
    
    public void setDefaultLocDetailses(Set defaultLocDetailses) {
        this.defaultLocDetailses = defaultLocDetailses;
    }




}


