package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * BillPaymentDuedate generated by hbm2java
 */
public class BillPaymentDuedate implements java.io.Serializable {

    private BigDecimal slno;
    private String billtype;
    private BigDecimal noofdays;
    private String category;
    private Date fromDate;
    private Date toDate;
    private Date entryDate;
    private String status;
    private Date checkerDate;

    public BillPaymentDuedate() {
    }

    public BillPaymentDuedate(BigDecimal slno) {
        this.slno = slno;
    }

    public BillPaymentDuedate(BigDecimal slno, String billtype, BigDecimal noofdays, String category, Date fromDate, Date toDate, Date entryDate, String status,Date checkerDate) {
        this.slno = slno;
        this.billtype = billtype;
        this.noofdays = noofdays;
        this.category = category;
        this.fromDate = fromDate;
        this.toDate = toDate;
        this.entryDate = entryDate;
        this.status = status;
        this.checkerDate = checkerDate;

    }

    public BigDecimal getSlno() {
        return this.slno;
    }

    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }

    public String getBilltype() {
        return this.billtype;
    }

    public void setBilltype(String billtype) {
        this.billtype = billtype;
    }

    public BigDecimal getNoofdays() {
        return this.noofdays;
    }

    public void setNoofdays(BigDecimal noofdays) {
        this.noofdays = noofdays;
    }

    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Date getFromDate() {
        return fromDate;
    }

    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }

    public Date getToDate() {
        return toDate;
    }

    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }

    public Date getEntryDate() {
        return entryDate;
    }

    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getCheckerDate() {
        return checkerDate;
    }

    public void setCheckerDate(Date checkerDate) {
        this.checkerDate = checkerDate;
    }
    
    

}
