package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BillReceiveCorp generated by hbm2java
 */
public class BillReceiveCorp  implements java.io.Serializable {


     private BigDecimal uniqueId;
     private Corporates corporates;
     private BigDecimal weekId;
     private BigDecimal toalnet;
     private String disburseStatus;
     private BigDecimal disburseAmount;
     private BigDecimal pendingAmount;
     private BigDecimal revisedrefund;
     private BigDecimal revisedpaybale;
     private Date billingDate;
     private BigDecimal billYear;
     private BigDecimal revisionNo;
     private String remarks;
     private String adjustmentflag;
     private BigDecimal adjustmentAmount;
     private String billType;
     private String billCategory;
     private String billPriority;
     private BigDecimal netDsm;
     private Date billDueDate;
     private Set tempPaymentDisbursements = new HashSet(0);
     private Set tempRefundBillCorps = new HashSet(0);
     private Set paymentDisbursements = new HashSet(0);

    public BillReceiveCorp() {
    }

	
    public BillReceiveCorp(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }
    public BillReceiveCorp(BigDecimal uniqueId, Corporates corporates, BigDecimal weekId, BigDecimal toalnet, String disburseStatus, BigDecimal disburseAmount, BigDecimal pendingAmount, BigDecimal revisedrefund, BigDecimal revisedpaybale, Date billingDate, BigDecimal billYear, BigDecimal revisionNo, String remarks, String adjustmentflag, BigDecimal adjustmentAmount, String billType, String billCategory, String billPriority, BigDecimal netDsm, Date billDueDate, Set tempPaymentDisbursements, Set tempRefundBillCorps, Set paymentDisbursements) {
       this.uniqueId = uniqueId;
       this.corporates = corporates;
       this.weekId = weekId;
       this.toalnet = toalnet;
       this.disburseStatus = disburseStatus;
       this.disburseAmount = disburseAmount;
       this.pendingAmount = pendingAmount;
       this.revisedrefund = revisedrefund;
       this.revisedpaybale = revisedpaybale;
       this.billingDate = billingDate;
       this.billYear = billYear;
       this.revisionNo = revisionNo;
       this.remarks = remarks;
       this.adjustmentflag = adjustmentflag;
       this.adjustmentAmount = adjustmentAmount;
       this.billType = billType;
       this.billCategory = billCategory;
       this.billPriority = billPriority;
       this.netDsm = netDsm;
       this.billDueDate = billDueDate;
       this.tempPaymentDisbursements = tempPaymentDisbursements;
       this.tempRefundBillCorps = tempRefundBillCorps;
       this.paymentDisbursements = paymentDisbursements;
    }
   
    public BigDecimal getUniqueId() {
        return this.uniqueId;
    }
    
    public void setUniqueId(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }
    public Corporates getCorporates() {
        return this.corporates;
    }
    
    public void setCorporates(Corporates corporates) {
        this.corporates = corporates;
    }
    public BigDecimal getWeekId() {
        return this.weekId;
    }
    
    public void setWeekId(BigDecimal weekId) {
        this.weekId = weekId;
    }
    public BigDecimal getToalnet() {
        return this.toalnet;
    }
    
    public void setToalnet(BigDecimal toalnet) {
        this.toalnet = toalnet;
    }
    public String getDisburseStatus() {
        return this.disburseStatus;
    }
    
    public void setDisburseStatus(String disburseStatus) {
        this.disburseStatus = disburseStatus;
    }
    public BigDecimal getDisburseAmount() {
        return this.disburseAmount;
    }
    
    public void setDisburseAmount(BigDecimal disburseAmount) {
        this.disburseAmount = disburseAmount;
    }
    public BigDecimal getPendingAmount() {
        return this.pendingAmount;
    }
    
    public void setPendingAmount(BigDecimal pendingAmount) {
        this.pendingAmount = pendingAmount;
    }
    public BigDecimal getRevisedrefund() {
        return this.revisedrefund;
    }
    
    public void setRevisedrefund(BigDecimal revisedrefund) {
        this.revisedrefund = revisedrefund;
    }
    public BigDecimal getRevisedpaybale() {
        return this.revisedpaybale;
    }
    
    public void setRevisedpaybale(BigDecimal revisedpaybale) {
        this.revisedpaybale = revisedpaybale;
    }
    public Date getBillingDate() {
        return this.billingDate;
    }
    
    public void setBillingDate(Date billingDate) {
        this.billingDate = billingDate;
    }
    public BigDecimal getBillYear() {
        return this.billYear;
    }
    
    public void setBillYear(BigDecimal billYear) {
        this.billYear = billYear;
    }
    public BigDecimal getRevisionNo() {
        return this.revisionNo;
    }
    
    public void setRevisionNo(BigDecimal revisionNo) {
        this.revisionNo = revisionNo;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getAdjustmentflag() {
        return this.adjustmentflag;
    }
    
    public void setAdjustmentflag(String adjustmentflag) {
        this.adjustmentflag = adjustmentflag;
    }
    public BigDecimal getAdjustmentAmount() {
        return this.adjustmentAmount;
    }
    
    public void setAdjustmentAmount(BigDecimal adjustmentAmount) {
        this.adjustmentAmount = adjustmentAmount;
    }
    public String getBillType() {
        return this.billType;
    }
    
    public void setBillType(String billType) {
        this.billType = billType;
    }
    public String getBillCategory() {
        return this.billCategory;
    }
    
    public void setBillCategory(String billCategory) {
        this.billCategory = billCategory;
    }
    public String getBillPriority() {
        return this.billPriority;
    }
    
    public void setBillPriority(String billPriority) {
        this.billPriority = billPriority;
    }
    public BigDecimal getNetDsm() {
        return this.netDsm;
    }
    
    public void setNetDsm(BigDecimal netDsm) {
        this.netDsm = netDsm;
    }
    public Date getBillDueDate() {
        return this.billDueDate;
    }
    
    public void setBillDueDate(Date billDueDate) {
        this.billDueDate = billDueDate;
    }
    public Set getTempPaymentDisbursements() {
        return this.tempPaymentDisbursements;
    }
    
    public void setTempPaymentDisbursements(Set tempPaymentDisbursements) {
        this.tempPaymentDisbursements = tempPaymentDisbursements;
    }
    public Set getTempRefundBillCorps() {
        return this.tempRefundBillCorps;
    }
    
    public void setTempRefundBillCorps(Set tempRefundBillCorps) {
        this.tempRefundBillCorps = tempRefundBillCorps;
    }
    public Set getPaymentDisbursements() {
        return this.paymentDisbursements;
    }
    
    public void setPaymentDisbursements(Set paymentDisbursements) {
        this.paymentDisbursements = paymentDisbursements;
    }




}


