package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * BillPriority generated by hbm2java
 */
public class BillPriority  implements java.io.Serializable {


     private BigDecimal slno;
     private String priorityname;
     private BigDecimal orderby;

    public BillPriority() {
    }

	
    public BillPriority(BigDecimal slno) {
        this.slno = slno;
    }
    public BillPriority(BigDecimal slno, String priorityname, BigDecimal orderby) {
       this.slno = slno;
       this.priorityname = priorityname;
       this.orderby = orderby;
    }
   
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }
    public String getPriorityname() {
        return this.priorityname;
    }
    
    public void setPriorityname(String priorityname) {
        this.priorityname = priorityname;
    }
    public BigDecimal getOrderby() {
        return this.orderby;
    }
    
    public void setOrderby(BigDecimal orderby) {
        this.orderby = orderby;
    }




}


