package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1



/**
 * ConstantsMaster generated by hbm2java
 */
public class ConstantsMaster  implements java.io.Serializable {


     private String name;
     private String description;
     private String value;

    public ConstantsMaster() {
    }

	
    public ConstantsMaster(String name) {
        this.name = name;
    }
    public ConstantsMaster(String name, String description, String value) {
       this.name = name;
       this.description = description;
       this.value = value;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


