package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Corporates generated by hbm2java
 */
public class Corporates  implements java.io.Serializable {


     private int corporateId;
     private String corporateName;
     private String sname;
     private String address;
     private String location;
     private String state;
     private String dsmContact;
     private String rrasContact;
     private String congContact;
     private String rectContact;
     private String mobile;
     private String office;
     private Date entryDate;
     private String corporateType;
     private String validity;
     private String blockRemarks;
     private String subAccountNumber;
     private BigDecimal outStanding;
     private String partyCode;
     private String bankAccName;
     private Set billEntityFrases = new HashSet(0);
     private Set interestDetailses = new HashSet(0);
     private Set tempDisbInterestDetailses = new HashSet(0);
     private Set billPayableCorps = new HashSet(0);
     private Set bankStatements = new HashSet(0);
     private Set userDetailses = new HashSet(0);
     private Set tempBillPayableEntityDsms = new HashSet(0);
     private Set tempBillEntityFrases = new HashSet(0);
     private Set entiteses = new HashSet(0);
     private Set tempInterestDetailses = new HashSet(0);
     private Set disbursedInterestDetailses = new HashSet(0);
     private Set tempBillReceiveCorps = new HashSet(0);
     private Set billReceiveCorps = new HashSet(0);
     private Set tempBillPayableEntityRrases = new HashSet(0);
     private Set billReceiveEntityDsms = new HashSet(0);
     private Set billPayableEntityRrases = new HashSet(0);
     private Set mappingBillBanks = new HashSet(0);
     private Set tempBillPayableCorps = new HashSet(0);
     private Set tempBillReceiveEntityDsms = new HashSet(0);
     private Set tempBillReceiveEntityRrases = new HashSet(0);
     private Set paymentDisbursements = new HashSet(0);
     private Set tempMappingBillBanks = new HashSet(0);
     private Set tempRefundBillCorps = new HashSet(0);
     private Set billPayableEntityDsms = new HashSet(0);
     private Set billReceiveEntityRrases = new HashSet(0);
     private Set tempPaymentDisbursements = new HashSet(0);
     private Set billEntityAgcs = new HashSet(0);
     private Set tempBillEntityAgcs = new HashSet(0);
     private Set defaultLocDetailses = new HashSet(0);

    public Corporates() {
    }

	
    public Corporates(int corporateId) {
        this.corporateId = corporateId;
    }
    public Corporates(int corporateId, String corporateName, String sname, String address, String location, String state, String dsmContact, String rrasContact, String congContact, String rectContact, String mobile, String office, Date entryDate, String corporateType, String validity, String blockRemarks, String subAccountNumber, BigDecimal outStanding, String partyCode,String bankAccName, Set billEntityFrases, Set interestDetailses, Set tempDisbInterestDetailses, Set billPayableCorps, Set bankStatements, Set userDetailses, Set tempBillPayableEntityDsms, Set tempBillEntityFrases, Set entiteses, Set tempInterestDetailses, Set disbursedInterestDetailses, Set tempBillReceiveCorps, Set billReceiveCorps, Set tempBillPayableEntityRrases, Set billReceiveEntityDsms, Set billPayableEntityRrases, Set mappingBillBanks, Set tempBillPayableCorps, Set tempBillReceiveEntityDsms, Set tempBillReceiveEntityRrases, Set paymentDisbursements, Set tempMappingBillBanks, Set tempRefundBillCorps, Set billPayableEntityDsms, Set billReceiveEntityRrases, Set tempPaymentDisbursements, Set billEntityAgcs, Set tempBillEntityAgcs, Set defaultLocDetailses) {
       this.corporateId = corporateId;
       this.corporateName = corporateName;
       this.sname = sname;
       this.address = address;
       this.location = location;
       this.state = state;
       this.dsmContact = dsmContact;
       this.rrasContact = rrasContact;
       this.congContact = congContact;
       this.rectContact = rectContact;
       this.mobile = mobile;
       this.office = office;
       this.entryDate = entryDate;
       this.corporateType = corporateType;
       this.validity = validity;
       this.blockRemarks = blockRemarks;
       this.subAccountNumber = subAccountNumber;
       this.outStanding = outStanding;
       this.partyCode = partyCode;
       this.bankAccName = bankAccName;
       this.billEntityFrases = billEntityFrases;
       this.interestDetailses = interestDetailses;
       this.tempDisbInterestDetailses = tempDisbInterestDetailses;
       this.billPayableCorps = billPayableCorps;
       this.bankStatements = bankStatements;
       this.userDetailses = userDetailses;
       this.tempBillPayableEntityDsms = tempBillPayableEntityDsms;
       this.tempBillEntityFrases = tempBillEntityFrases;
       this.entiteses = entiteses;
       this.tempInterestDetailses = tempInterestDetailses;
       this.disbursedInterestDetailses = disbursedInterestDetailses;
       this.tempBillReceiveCorps = tempBillReceiveCorps;
       this.billReceiveCorps = billReceiveCorps;
       this.tempBillPayableEntityRrases = tempBillPayableEntityRrases;
       this.billReceiveEntityDsms = billReceiveEntityDsms;
       this.billPayableEntityRrases = billPayableEntityRrases;
       this.mappingBillBanks = mappingBillBanks;
       this.tempBillPayableCorps = tempBillPayableCorps;
       this.tempBillReceiveEntityDsms = tempBillReceiveEntityDsms;
       this.tempBillReceiveEntityRrases = tempBillReceiveEntityRrases;
       this.paymentDisbursements = paymentDisbursements;
       this.tempMappingBillBanks = tempMappingBillBanks;
       this.tempRefundBillCorps = tempRefundBillCorps;
       this.billPayableEntityDsms = billPayableEntityDsms;
       this.billReceiveEntityRrases = billReceiveEntityRrases;
       this.tempPaymentDisbursements = tempPaymentDisbursements;
       this.billEntityAgcs = billEntityAgcs;
       this.tempBillEntityAgcs = tempBillEntityAgcs;
       this.defaultLocDetailses = defaultLocDetailses;
    }
   
    public int getCorporateId() {
        return this.corporateId;
    }
    
    public void setCorporateId(int corporateId) {
        this.corporateId = corporateId;
    }
    public String getCorporateName() {
        return this.corporateName;
    }
    
    public void setCorporateName(String corporateName) {
        this.corporateName = corporateName;
    }
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getDsmContact() {
        return this.dsmContact;
    }
    
    public void setDsmContact(String dsmContact) {
        this.dsmContact = dsmContact;
    }
    public String getRrasContact() {
        return this.rrasContact;
    }
    
    public void setRrasContact(String rrasContact) {
        this.rrasContact = rrasContact;
    }
    public String getCongContact() {
        return this.congContact;
    }
    
    public void setCongContact(String congContact) {
        this.congContact = congContact;
    }
    public String getRectContact() {
        return this.rectContact;
    }
    
    public void setRectContact(String rectContact) {
        this.rectContact = rectContact;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getOffice() {
        return this.office;
    }
    
    public void setOffice(String office) {
        this.office = office;
    }
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
    public String getCorporateType() {
        return this.corporateType;
    }
    
    public void setCorporateType(String corporateType) {
        this.corporateType = corporateType;
    }
    public String getValidity() {
        return this.validity;
    }
    
    public void setValidity(String validity) {
        this.validity = validity;
    }
    public String getBlockRemarks() {
        return this.blockRemarks;
    }
    
    public void setBlockRemarks(String blockRemarks) {
        this.blockRemarks = blockRemarks;
    }
    public String getSubAccountNumber() {
        return this.subAccountNumber;
    }
    
    public void setSubAccountNumber(String subAccountNumber) {
        this.subAccountNumber = subAccountNumber;
    }
    public BigDecimal getOutStanding() {
        return this.outStanding;
    }
    
    public void setOutStanding(BigDecimal outStanding) {
        this.outStanding = outStanding;
    }
    public String getPartyCode() {
        return this.partyCode;
    }
    
    public void setPartyCode(String partyCode) {
        this.partyCode = partyCode;
    }

    public String getBankAccName() {
        return bankAccName;
    }

    public void setBankAccName(String bankAccName) {
        this.bankAccName = bankAccName;
    }
    
    
    public Set getBillEntityFrases() {
        return this.billEntityFrases;
    }
    
    public void setBillEntityFrases(Set billEntityFrases) {
        this.billEntityFrases = billEntityFrases;
    }
    public Set getInterestDetailses() {
        return this.interestDetailses;
    }
    
    public void setInterestDetailses(Set interestDetailses) {
        this.interestDetailses = interestDetailses;
    }
    public Set getTempDisbInterestDetailses() {
        return this.tempDisbInterestDetailses;
    }
    
    public void setTempDisbInterestDetailses(Set tempDisbInterestDetailses) {
        this.tempDisbInterestDetailses = tempDisbInterestDetailses;
    }
    public Set getBillPayableCorps() {
        return this.billPayableCorps;
    }
    
    public void setBillPayableCorps(Set billPayableCorps) {
        this.billPayableCorps = billPayableCorps;
    }
    public Set getBankStatements() {
        return this.bankStatements;
    }
    
    public void setBankStatements(Set bankStatements) {
        this.bankStatements = bankStatements;
    }
    public Set getUserDetailses() {
        return this.userDetailses;
    }
    
    public void setUserDetailses(Set userDetailses) {
        this.userDetailses = userDetailses;
    }
    public Set getTempBillPayableEntityDsms() {
        return this.tempBillPayableEntityDsms;
    }
    
    public void setTempBillPayableEntityDsms(Set tempBillPayableEntityDsms) {
        this.tempBillPayableEntityDsms = tempBillPayableEntityDsms;
    }
    public Set getTempBillEntityFrases() {
        return this.tempBillEntityFrases;
    }
    
    public void setTempBillEntityFrases(Set tempBillEntityFrases) {
        this.tempBillEntityFrases = tempBillEntityFrases;
    }
    public Set getEntiteses() {
        return this.entiteses;
    }
    
    public void setEntiteses(Set entiteses) {
        this.entiteses = entiteses;
    }
    public Set getTempInterestDetailses() {
        return this.tempInterestDetailses;
    }
    
    public void setTempInterestDetailses(Set tempInterestDetailses) {
        this.tempInterestDetailses = tempInterestDetailses;
    }
    public Set getDisbursedInterestDetailses() {
        return this.disbursedInterestDetailses;
    }
    
    public void setDisbursedInterestDetailses(Set disbursedInterestDetailses) {
        this.disbursedInterestDetailses = disbursedInterestDetailses;
    }
    public Set getTempBillReceiveCorps() {
        return this.tempBillReceiveCorps;
    }
    
    public void setTempBillReceiveCorps(Set tempBillReceiveCorps) {
        this.tempBillReceiveCorps = tempBillReceiveCorps;
    }
    public Set getBillReceiveCorps() {
        return this.billReceiveCorps;
    }
    
    public void setBillReceiveCorps(Set billReceiveCorps) {
        this.billReceiveCorps = billReceiveCorps;
    }
    public Set getTempBillPayableEntityRrases() {
        return this.tempBillPayableEntityRrases;
    }
    
    public void setTempBillPayableEntityRrases(Set tempBillPayableEntityRrases) {
        this.tempBillPayableEntityRrases = tempBillPayableEntityRrases;
    }
    public Set getBillReceiveEntityDsms() {
        return this.billReceiveEntityDsms;
    }
    
    public void setBillReceiveEntityDsms(Set billReceiveEntityDsms) {
        this.billReceiveEntityDsms = billReceiveEntityDsms;
    }
    public Set getBillPayableEntityRrases() {
        return this.billPayableEntityRrases;
    }
    
    public void setBillPayableEntityRrases(Set billPayableEntityRrases) {
        this.billPayableEntityRrases = billPayableEntityRrases;
    }
    public Set getMappingBillBanks() {
        return this.mappingBillBanks;
    }
    
    public void setMappingBillBanks(Set mappingBillBanks) {
        this.mappingBillBanks = mappingBillBanks;
    }
    public Set getTempBillPayableCorps() {
        return this.tempBillPayableCorps;
    }
    
    public void setTempBillPayableCorps(Set tempBillPayableCorps) {
        this.tempBillPayableCorps = tempBillPayableCorps;
    }
    public Set getTempBillReceiveEntityDsms() {
        return this.tempBillReceiveEntityDsms;
    }
    
    public void setTempBillReceiveEntityDsms(Set tempBillReceiveEntityDsms) {
        this.tempBillReceiveEntityDsms = tempBillReceiveEntityDsms;
    }
    public Set getTempBillReceiveEntityRrases() {
        return this.tempBillReceiveEntityRrases;
    }
    
    public void setTempBillReceiveEntityRrases(Set tempBillReceiveEntityRrases) {
        this.tempBillReceiveEntityRrases = tempBillReceiveEntityRrases;
    }
    public Set getPaymentDisbursements() {
        return this.paymentDisbursements;
    }
    
    public void setPaymentDisbursements(Set paymentDisbursements) {
        this.paymentDisbursements = paymentDisbursements;
    }
    public Set getTempMappingBillBanks() {
        return this.tempMappingBillBanks;
    }
    
    public void setTempMappingBillBanks(Set tempMappingBillBanks) {
        this.tempMappingBillBanks = tempMappingBillBanks;
    }
    public Set getTempRefundBillCorps() {
        return this.tempRefundBillCorps;
    }
    
    public void setTempRefundBillCorps(Set tempRefundBillCorps) {
        this.tempRefundBillCorps = tempRefundBillCorps;
    }
    public Set getBillPayableEntityDsms() {
        return this.billPayableEntityDsms;
    }
    
    public void setBillPayableEntityDsms(Set billPayableEntityDsms) {
        this.billPayableEntityDsms = billPayableEntityDsms;
    }
    public Set getBillReceiveEntityRrases() {
        return this.billReceiveEntityRrases;
    }
    
    public void setBillReceiveEntityRrases(Set billReceiveEntityRrases) {
        this.billReceiveEntityRrases = billReceiveEntityRrases;
    }
    public Set getTempPaymentDisbursements() {
        return this.tempPaymentDisbursements;
    }
    
    public void setTempPaymentDisbursements(Set tempPaymentDisbursements) {
        this.tempPaymentDisbursements = tempPaymentDisbursements;
    }
    public Set getBillEntityAgcs() {
        return this.billEntityAgcs;
    }
    
    public void setBillEntityAgcs(Set billEntityAgcs) {
        this.billEntityAgcs = billEntityAgcs;
    }
    public Set getTempBillEntityAgcs() {
        return this.tempBillEntityAgcs;
    }
    
    public void setTempBillEntityAgcs(Set tempBillEntityAgcs) {
        this.tempBillEntityAgcs = tempBillEntityAgcs;
    }
    public Set getDefaultLocDetailses() {
        return this.defaultLocDetailses;
    }
    
    public void setDefaultLocDetailses(Set defaultLocDetailses) {
        this.defaultLocDetailses = defaultLocDetailses;
    }




}


