package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DefaultLocDetails generated by hbm2java
 */
public class DefaultLocDetails  implements java.io.Serializable {


     private BigDecimal slno;
     private Corporates corporates;
     private BillPayableCorp billPayableCorp;
     private BigDecimal weekid;
     private BigDecimal billYear;
     private BigDecimal billAmount;
     private Date entryDate;
     private String billType;
     private String billCategory;
     private String locFlag;
     private Set letterOfCredits = new HashSet(0);

    public DefaultLocDetails() {
    }

	
    public DefaultLocDetails(BigDecimal slno) {
        this.slno = slno;
    }
    public DefaultLocDetails(BigDecimal slno, Corporates corporates, BillPayableCorp billPayableCorp, BigDecimal weekid, BigDecimal billYear, BigDecimal billAmount, Date entryDate, String billType, String billCategory, String locFlag, Set letterOfCredits) {
       this.slno = slno;
       this.corporates = corporates;
       this.billPayableCorp = billPayableCorp;
       this.weekid = weekid;
       this.billYear = billYear;
       this.billAmount = billAmount;
       this.entryDate = entryDate;
       this.billType = billType;
       this.billCategory = billCategory;
       this.locFlag = locFlag;
       this.letterOfCredits = letterOfCredits;
    }
   
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }
    public Corporates getCorporates() {
        return this.corporates;
    }
    
    public void setCorporates(Corporates corporates) {
        this.corporates = corporates;
    }
    public BillPayableCorp getBillPayableCorp() {
        return this.billPayableCorp;
    }
    
    public void setBillPayableCorp(BillPayableCorp billPayableCorp) {
        this.billPayableCorp = billPayableCorp;
    }
    public BigDecimal getWeekid() {
        return this.weekid;
    }
    
    public void setWeekid(BigDecimal weekid) {
        this.weekid = weekid;
    }
    public BigDecimal getBillYear() {
        return this.billYear;
    }
    
    public void setBillYear(BigDecimal billYear) {
        this.billYear = billYear;
    }
    public BigDecimal getBillAmount() {
        return this.billAmount;
    }
    
    public void setBillAmount(BigDecimal billAmount) {
        this.billAmount = billAmount;
    }
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
    public String getBillType() {
        return this.billType;
    }
    
    public void setBillType(String billType) {
        this.billType = billType;
    }
    public String getBillCategory() {
        return this.billCategory;
    }
    
    public void setBillCategory(String billCategory) {
        this.billCategory = billCategory;
    }
    public String getLocFlag() {
        return this.locFlag;
    }
    
    public void setLocFlag(String locFlag) {
        this.locFlag = locFlag;
    }
    public Set getLetterOfCredits() {
        return this.letterOfCredits;
    }
    
    public void setLetterOfCredits(Set letterOfCredits) {
        this.letterOfCredits = letterOfCredits;
    }




}


