package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Documents generated by hbm2java
 */
public class Documents  implements java.io.Serializable {


     private String documentNo;
     private String description;
     private String filename;
     private String status;
     private String filesize;
     private String filetype;
     private Date uploadDateByMaker;
     private Date checkDateByChecker;
     private String documentSetNo;

    public Documents() {
    }

	
    public Documents(String documentNo) {
        this.documentNo = documentNo;
    }
    public Documents(String documentNo, String description, String filename, String status, String filesize, String filetype, Date uploadDateByMaker, Date checkDateByChecker, String documentSetNo) {
       this.documentNo = documentNo;
       this.description = description;
       this.filename = filename;
       this.status = status;
       this.filesize = filesize;
       this.filetype = filetype;
       this.uploadDateByMaker = uploadDateByMaker;
       this.checkDateByChecker = checkDateByChecker;
       this.documentSetNo = documentSetNo;
    }
   
    public String getDocumentNo() {
        return this.documentNo;
    }
    
    public void setDocumentNo(String documentNo) {
        this.documentNo = documentNo;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getFilesize() {
        return this.filesize;
    }
    
    public void setFilesize(String filesize) {
        this.filesize = filesize;
    }
    public String getFiletype() {
        return this.filetype;
    }
    
    public void setFiletype(String filetype) {
        this.filetype = filetype;
    }
    public Date getUploadDateByMaker() {
        return this.uploadDateByMaker;
    }
    
    public void setUploadDateByMaker(Date uploadDateByMaker) {
        this.uploadDateByMaker = uploadDateByMaker;
    }
    public Date getCheckDateByChecker() {
        return this.checkDateByChecker;
    }
    
    public void setCheckDateByChecker(Date checkDateByChecker) {
        this.checkDateByChecker = checkDateByChecker;
    }
    public String getDocumentSetNo() {
        return this.documentSetNo;
    }
    
    public void setDocumentSetNo(String documentSetNo) {
        this.documentSetNo = documentSetNo;
    }




}


