package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * DsnDisbursement generated by hbm2java
 */
public class DsnDisbursement  implements java.io.Serializable {


     private BigDecimal slno;
     private BankStatement bankStatement;
     private BigDecimal dsnAmount;
     private BigDecimal mainPoolBalance;
     private Date entryTime;
     private String checkerStatus;

    public DsnDisbursement() {
    }

	
    public DsnDisbursement(BigDecimal slno) {
        this.slno = slno;
    }
    public DsnDisbursement(BigDecimal slno, BankStatement bankStatement, BigDecimal dsnAmount, BigDecimal mainPoolBalance, Date entryTime, String checkerStatus) {
       this.slno = slno;
       this.bankStatement = bankStatement;
       this.dsnAmount = dsnAmount;
       this.mainPoolBalance = mainPoolBalance;
       this.entryTime = entryTime;
       this.checkerStatus = checkerStatus;
    }
   
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }
    public BankStatement getBankStatement() {
        return this.bankStatement;
    }
    
    public void setBankStatement(BankStatement bankStatement) {
        this.bankStatement = bankStatement;
    }
    public BigDecimal getDsnAmount() {
        return this.dsnAmount;
    }
    
    public void setDsnAmount(BigDecimal dsnAmount) {
        this.dsnAmount = dsnAmount;
    }
    public BigDecimal getMainPoolBalance() {
        return this.mainPoolBalance;
    }
    
    public void setMainPoolBalance(BigDecimal mainPoolBalance) {
        this.mainPoolBalance = mainPoolBalance;
    }
    public Date getEntryTime() {
        return this.entryTime;
    }
    
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }
    public String getCheckerStatus() {
        return this.checkerStatus;
    }
    
    public void setCheckerStatus(String checkerStatus) {
        this.checkerStatus = checkerStatus;
    }




}


