package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DsnFileDetails generated by hbm2java
 */
public class DsnFileDetails  implements java.io.Serializable {


     private BigDecimal slno;
     private BankStatement bankStatement;
     private String fileName;
     private String checkerStatus;
     private BigDecimal mappedBalance;

    public DsnFileDetails() {
    }

	
    public DsnFileDetails(BigDecimal slno) {
        this.slno = slno;
    }
    public DsnFileDetails(BigDecimal slno, BankStatement bankStatement, String fileName, String checkerStatus, BigDecimal mappedBalance) {
       this.slno = slno;
       this.bankStatement = bankStatement;
       this.fileName = fileName;
       this.checkerStatus = checkerStatus;
       this.mappedBalance = mappedBalance;
    }
   
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }
    public BankStatement getBankStatement() {
        return this.bankStatement;
    }
    
    public void setBankStatement(BankStatement bankStatement) {
        this.bankStatement = bankStatement;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public String getCheckerStatus() {
        return this.checkerStatus;
    }
    
    public void setCheckerStatus(String checkerStatus) {
        this.checkerStatus = checkerStatus;
    }
    public BigDecimal getMappedBalance() {
        return this.mappedBalance;
    }
    
    public void setMappedBalance(BigDecimal mappedBalance) {
        this.mappedBalance = mappedBalance;
    }




}


