package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1



/**
 * EntityType generated by hbm2java
 */
public class EntityType  implements java.io.Serializable {


     private long typeId;
     private String entityType;

    public EntityType() {
    }

    public EntityType(long typeId, String entityType) {
       this.typeId = typeId;
       this.entityType = entityType;
    }
   
    public long getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(long typeId) {
        this.typeId = typeId;
    }
    public String getEntityType() {
        return this.entityType;
    }
    
    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }




}


