package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * LetterOfCredit generated by hbm2java
 */
public class LetterOfCredit  implements java.io.Serializable {


     private BigDecimal lcId;
     private DefaultLocDetails defaultLocDetails;
     private Date lcFromdate;
     private Date lcTodate;
     private String constituent;
     private String lastFyAvg;
     private BigDecimal lcCondition;
     private String lcIssueBank;
     private String lcIssueBranch;
     private String lcAmount;
     private String remarks;
     private String finYear;
     private Date entryDate;
     private BigDecimal expFlag;
     private String fileName;

    public LetterOfCredit() {
    }

	
    public LetterOfCredit(BigDecimal lcId) {
        this.lcId = lcId;
    }
    public LetterOfCredit(BigDecimal lcId, DefaultLocDetails defaultLocDetails, Date lcFromdate, Date lcTodate, String constituent, String lastFyAvg, BigDecimal lcCondition, String lcIssueBank, String lcIssueBranch, String lcAmount, String remarks, String finYear, Date entryDate, BigDecimal expFlag, String fileName) {
       this.lcId = lcId;
       this.defaultLocDetails = defaultLocDetails;
       this.lcFromdate = lcFromdate;
       this.lcTodate = lcTodate;
       this.constituent = constituent;
       this.lastFyAvg = lastFyAvg;
       this.lcCondition = lcCondition;
       this.lcIssueBank = lcIssueBank;
       this.lcIssueBranch = lcIssueBranch;
       this.lcAmount = lcAmount;
       this.remarks = remarks;
       this.finYear = finYear;
       this.entryDate = entryDate;
       this.expFlag = expFlag;
       this.fileName = fileName;
    }
   
    public BigDecimal getLcId() {
        return this.lcId;
    }
    
    public void setLcId(BigDecimal lcId) {
        this.lcId = lcId;
    }
    public DefaultLocDetails getDefaultLocDetails() {
        return this.defaultLocDetails;
    }
    
    public void setDefaultLocDetails(DefaultLocDetails defaultLocDetails) {
        this.defaultLocDetails = defaultLocDetails;
    }
    public Date getLcFromdate() {
        return this.lcFromdate;
    }
    
    public void setLcFromdate(Date lcFromdate) {
        this.lcFromdate = lcFromdate;
    }
    public Date getLcTodate() {
        return this.lcTodate;
    }
    
    public void setLcTodate(Date lcTodate) {
        this.lcTodate = lcTodate;
    }
    public String getConstituent() {
        return this.constituent;
    }
    
    public void setConstituent(String constituent) {
        this.constituent = constituent;
    }
    public String getLastFyAvg() {
        return this.lastFyAvg;
    }
    
    public void setLastFyAvg(String lastFyAvg) {
        this.lastFyAvg = lastFyAvg;
    }
    public BigDecimal getLcCondition() {
        return this.lcCondition;
    }
    
    public void setLcCondition(BigDecimal lcCondition) {
        this.lcCondition = lcCondition;
    }
    public String getLcIssueBank() {
        return this.lcIssueBank;
    }
    
    public void setLcIssueBank(String lcIssueBank) {
        this.lcIssueBank = lcIssueBank;
    }
    public String getLcIssueBranch() {
        return this.lcIssueBranch;
    }
    
    public void setLcIssueBranch(String lcIssueBranch) {
        this.lcIssueBranch = lcIssueBranch;
    }
    public String getLcAmount() {
        return this.lcAmount;
    }
    
    public void setLcAmount(String lcAmount) {
        this.lcAmount = lcAmount;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getFinYear() {
        return this.finYear;
    }
    
    public void setFinYear(String finYear) {
        this.finYear = finYear;
    }
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
    public BigDecimal getExpFlag() {
        return this.expFlag;
    }
    
    public void setExpFlag(BigDecimal expFlag) {
        this.expFlag = expFlag;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }




}


