package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * MappingBillBank generated by hbm2java
 */
public class MappingBillBank implements java.io.Serializable {

    private BigDecimal uniqueId;
    private Corporates corporates;
    private UserDetails userDetails;
    private BankStatement bankStatement;
    private BillPayableCorp billPayableCorp;
    private BigDecimal weekId;
    private String paymentCategory;
    private BigDecimal originalAmount;
    private BigDecimal mappedAmount;
    private BigDecimal pendingAmount;
    private String billType;
    private Date entryDate;
    private String checkerStatus;
    private String remarks;
    private BigDecimal pendingBankAmount;
    private Date entryTime;
    private BigDecimal poolBal;
    private BigDecimal poolAgcBal;
    private BigDecimal poolRrasBal;

    public MappingBillBank() {
    }

    public MappingBillBank(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }

    public MappingBillBank(BigDecimal uniqueId, Corporates corporates, UserDetails userDetails, BankStatement bankStatement, BillPayableCorp billPayableCorp, BigDecimal weekId, String paymentCategory, BigDecimal originalAmount, BigDecimal mappedAmount, BigDecimal pendingAmount, String billType, Date entryDate, String checkerStatus, String remarks, BigDecimal pendingBankAmount, Date entryTime, BigDecimal poolBal, BigDecimal poolAgcBal, BigDecimal poolRrasBal) {
        this.uniqueId = uniqueId;
        this.corporates = corporates;
        this.userDetails = userDetails;
        this.bankStatement = bankStatement;
        this.billPayableCorp = billPayableCorp;
        this.weekId = weekId;
        this.paymentCategory = paymentCategory;
        this.originalAmount = originalAmount;
        this.mappedAmount = mappedAmount;
        this.pendingAmount = pendingAmount;
        this.billType = billType;
        this.entryDate = entryDate;
        this.checkerStatus = checkerStatus;
        this.remarks = remarks;
        this.pendingBankAmount = pendingBankAmount;
        this.entryTime = entryTime;
        this.poolBal = poolBal;
        this.poolAgcBal = poolAgcBal;
        this.poolRrasBal = poolRrasBal;
    }

    public BigDecimal getUniqueId() {
        return this.uniqueId;
    }

    public void setUniqueId(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }

    public Corporates getCorporates() {
        return this.corporates;
    }

    public void setCorporates(Corporates corporates) {
        this.corporates = corporates;
    }

    public UserDetails getUserDetails() {
        return this.userDetails;
    }

    public void setUserDetails(UserDetails userDetails) {
        this.userDetails = userDetails;
    }

    public BankStatement getBankStatement() {
        return this.bankStatement;
    }

    public void setBankStatement(BankStatement bankStatement) {
        this.bankStatement = bankStatement;
    }

    public BillPayableCorp getBillPayableCorp() {
        return this.billPayableCorp;
    }

    public void setBillPayableCorp(BillPayableCorp billPayableCorp) {
        this.billPayableCorp = billPayableCorp;
    }

    public BigDecimal getWeekId() {
        return this.weekId;
    }

    public void setWeekId(BigDecimal weekId) {
        this.weekId = weekId;
    }

    public String getPaymentCategory() {
        return this.paymentCategory;
    }

    public void setPaymentCategory(String paymentCategory) {
        this.paymentCategory = paymentCategory;
    }

    public BigDecimal getOriginalAmount() {
        return this.originalAmount;
    }

    public void setOriginalAmount(BigDecimal originalAmount) {
        this.originalAmount = originalAmount;
    }

    public BigDecimal getMappedAmount() {
        return this.mappedAmount;
    }

    public void setMappedAmount(BigDecimal mappedAmount) {
        this.mappedAmount = mappedAmount;
    }

    public BigDecimal getPendingAmount() {
        return this.pendingAmount;
    }

    public void setPendingAmount(BigDecimal pendingAmount) {
        this.pendingAmount = pendingAmount;
    }

    public String getBillType() {
        return this.billType;
    }

    public void setBillType(String billType) {
        this.billType = billType;
    }

    public Date getEntryDate() {
        return this.entryDate;
    }

    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    public String getCheckerStatus() {
        return this.checkerStatus;
    }

    public void setCheckerStatus(String checkerStatus) {
        this.checkerStatus = checkerStatus;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public BigDecimal getPendingBankAmount() {
        return this.pendingBankAmount;
    }

    public void setPendingBankAmount(BigDecimal pendingBankAmount) {
        this.pendingBankAmount = pendingBankAmount;
    }

    public Date getEntryTime() {
        return entryTime;
    }

    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    public BigDecimal getPoolBal() {
        return poolBal;
    }

    public void setPoolBal(BigDecimal poolBal) {
        this.poolBal = poolBal;
    }

    public BigDecimal getPoolAgcBal() {
        return poolAgcBal;
    }

    public void setPoolAgcBal(BigDecimal poolAgcBal) {
        this.poolAgcBal = poolAgcBal;
    }

    public BigDecimal getPoolRrasBal() {
        return poolRrasBal;
    }

    public void setPoolRrasBal(BigDecimal poolRrasBal) {
        this.poolRrasBal = poolRrasBal;
    }

    
}
