package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * MappingRefundBank generated by hbm2java
 */
public class MappingRefundBank implements java.io.Serializable {

    private BigDecimal slno;
    private BankStatement bankStatement;
    private TempRefundBillCorp tempRefundBillCorp;
    private BigDecimal mappedAmount;
    private BigDecimal pendingAmount;
    private BigDecimal bankPendingAmount;
    private String checkerStatus;
    private Date entryDate;
    private String remarks;
    private Date entryTime;
    private BigDecimal poolBal;
    private BigDecimal poolAgcBal;
    private BigDecimal poolRrasBal;

    public MappingRefundBank() {
    }

    public MappingRefundBank(BigDecimal slno) {
        this.slno = slno;
    }

    public MappingRefundBank(BigDecimal slno, BankStatement bankStatement, TempRefundBillCorp tempRefundBillCorp, BigDecimal mappedAmount, BigDecimal pendingAmount, BigDecimal bankPendingAmount, String checkerStatus, Date entryDate, String remarks, Date entryTime, BigDecimal poolBal, BigDecimal poolAgcBal, BigDecimal poolRrasBal) {
        this.slno = slno;
        this.bankStatement = bankStatement;
        this.tempRefundBillCorp = tempRefundBillCorp;
        this.mappedAmount = mappedAmount;
        this.pendingAmount = pendingAmount;
        this.bankPendingAmount = bankPendingAmount;
        this.checkerStatus = checkerStatus;
        this.entryDate = entryDate;
        this.remarks = remarks;
        this.entryTime = entryTime;
        this.poolBal = poolBal;
        this.poolAgcBal = poolAgcBal;
        this.poolRrasBal = poolRrasBal;
    }

    public BigDecimal getSlno() {
        return this.slno;
    }

    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }

    public BankStatement getBankStatement() {
        return this.bankStatement;
    }

    public void setBankStatement(BankStatement bankStatement) {
        this.bankStatement = bankStatement;
    }

    public TempRefundBillCorp getTempRefundBillCorp() {
        return this.tempRefundBillCorp;
    }

    public void setTempRefundBillCorp(TempRefundBillCorp tempRefundBillCorp) {
        this.tempRefundBillCorp = tempRefundBillCorp;
    }

    public BigDecimal getMappedAmount() {
        return this.mappedAmount;
    }

    public void setMappedAmount(BigDecimal mappedAmount) {
        this.mappedAmount = mappedAmount;
    }

    public BigDecimal getPendingAmount() {
        return this.pendingAmount;
    }

    public void setPendingAmount(BigDecimal pendingAmount) {
        this.pendingAmount = pendingAmount;
    }

    public BigDecimal getBankPendingAmount() {
        return this.bankPendingAmount;
    }

    public void setBankPendingAmount(BigDecimal bankPendingAmount) {
        this.bankPendingAmount = bankPendingAmount;
    }

    public String getCheckerStatus() {
        return this.checkerStatus;
    }

    public void setCheckerStatus(String checkerStatus) {
        this.checkerStatus = checkerStatus;
    }

    public Date getEntryDate() {
        return this.entryDate;
    }

    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Date getEntryTime() {
        return entryTime;
    }

    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    public BigDecimal getPoolBal() {
        return poolBal;
    }

    public void setPoolBal(BigDecimal poolBal) {
        this.poolBal = poolBal;
    }

    public BigDecimal getPoolAgcBal() {
        return poolAgcBal;
    }

    public void setPoolAgcBal(BigDecimal poolAgcBal) {
        this.poolAgcBal = poolAgcBal;
    }

    public BigDecimal getPoolRrasBal() {
        return poolRrasBal;
    }

    public void setPoolRrasBal(BigDecimal poolRrasBal) {
        this.poolRrasBal = poolRrasBal;
    }

    
}
