package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * OutstandingYearCorp generated by hbm2java
 */
public class OutstandingYearCorp  implements java.io.Serializable {


     private BigDecimal slno;
     private Corporates corporates;
     private BigDecimal billYear;
     private BigDecimal outStanding;
     private Date entryDate;
     private String remarks;

    public OutstandingYearCorp() {
    }

	
    public OutstandingYearCorp(BigDecimal slno) {
        this.slno = slno;
    }
    public OutstandingYearCorp(BigDecimal slno, Corporates corporates, BigDecimal billYear, BigDecimal outStanding, Date entryDate, String remarks) {
       this.slno = slno;
       this.corporates = corporates;
       this.billYear = billYear;
       this.outStanding = outStanding;
       this.entryDate = entryDate;
       this.remarks = remarks;
    }
   
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }
    public Corporates getCorporates() {
        return this.corporates;
    }
    
    public void setCorporates(Corporates corporates) {
        this.corporates = corporates;
    }
    public BigDecimal getBillYear() {
        return this.billYear;
    }
    
    public void setBillYear(BigDecimal billYear) {
        this.billYear = billYear;
    }
    public BigDecimal getOutStanding() {
        return this.outStanding;
    }
    
    public void setOutStanding(BigDecimal outStanding) {
        this.outStanding = outStanding;
    }
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


