package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * PoolToInt generated by hbm2java
 */
public class PoolToInt  implements java.io.Serializable {


     private BigDecimal uniqueId;
     private BigDecimal refundAmt;
     private String documentSet;
     private String document;
     private Date entryDate;
     private String status;
     private Date makerDate;
     private Date checkerDate;
     private String remarks;
     private Date entryTime;
     private BigDecimal mainPoolBalance;
     private BigDecimal intPoolBalance;
      private BigDecimal poolAgcBal;
    private BigDecimal poolRrasBal;
    private BigDecimal intAgcBal;
    private BigDecimal intRrasBal;

    public PoolToInt() {
    }

	
    public PoolToInt(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }
    public PoolToInt(BigDecimal uniqueId, BigDecimal refundAmt, String documentSet, String document, Date entryDate, String status, Date makerDate, Date checkerDate, String remarks, Date entryTime, BigDecimal mainPoolBalance, BigDecimal intPoolBalance, BigDecimal poolAgcBal, BigDecimal poolRrasBal, BigDecimal intAgcBal, BigDecimal intRrasBal) {
       this.uniqueId = uniqueId;
       this.refundAmt = refundAmt;
       this.documentSet = documentSet;
       this.document = document;
       this.entryDate = entryDate;
       this.status = status;
       this.makerDate = makerDate;
       this.checkerDate = checkerDate;
       this.remarks = remarks;
       this.entryTime = entryTime;
       this.mainPoolBalance = mainPoolBalance;
       this.intPoolBalance = intPoolBalance;
        this.poolAgcBal = poolAgcBal;
        this.poolRrasBal = poolRrasBal;
        this.intAgcBal = intAgcBal;
        this.intRrasBal = intRrasBal;
    }
   
    public BigDecimal getUniqueId() {
        return this.uniqueId;
    }
    
    public void setUniqueId(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }
    public BigDecimal getRefundAmt() {
        return this.refundAmt;
    }
    
    public void setRefundAmt(BigDecimal refundAmt) {
        this.refundAmt = refundAmt;
    }
    public String getDocumentSet() {
        return this.documentSet;
    }
    
    public void setDocumentSet(String documentSet) {
        this.documentSet = documentSet;
    }
    public String getDocument() {
        return this.document;
    }
    
    public void setDocument(String document) {
        this.document = document;
    }
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getMakerDate() {
        return this.makerDate;
    }
    
    public void setMakerDate(Date makerDate) {
        this.makerDate = makerDate;
    }
    public Date getCheckerDate() {
        return this.checkerDate;
    }
    
    public void setCheckerDate(Date checkerDate) {
        this.checkerDate = checkerDate;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Serializable getEntryTime() {
        return this.entryTime;
    }
    
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }
    public BigDecimal getMainPoolBalance() {
        return this.mainPoolBalance;
    }
    
    public void setMainPoolBalance(BigDecimal mainPoolBalance) {
        this.mainPoolBalance = mainPoolBalance;
    }
    public BigDecimal getIntPoolBalance() {
        return this.intPoolBalance;
    }
    
    public void setIntPoolBalance(BigDecimal intPoolBalance) {
        this.intPoolBalance = intPoolBalance;
    }

    public BigDecimal getPoolAgcBal() {
        return poolAgcBal;
    }

    public void setPoolAgcBal(BigDecimal poolAgcBal) {
        this.poolAgcBal = poolAgcBal;
    }

    public BigDecimal getPoolRrasBal() {
        return poolRrasBal;
    }

    public void setPoolRrasBal(BigDecimal poolRrasBal) {
        this.poolRrasBal = poolRrasBal;
    }

    public BigDecimal getIntAgcBal() {
        return intAgcBal;
    }

    public void setIntAgcBal(BigDecimal intAgcBal) {
        this.intAgcBal = intAgcBal;
    }

    public BigDecimal getIntRrasBal() {
        return intRrasBal;
    }

    public void setIntRrasBal(BigDecimal intRrasBal) {
        this.intRrasBal = intRrasBal;
    }




}


