package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ReconciliationCorp generated by hbm2java
 */
public class ReconciliationCorp  implements java.io.Serializable {


     private BigDecimal slno;
     private Corporates corporates;
     private Date billEntryDate;
     private Date entryDate;
     private String billType;
     private Date billingDate;
     private BigDecimal revisionNo;
     private BigDecimal billYear;
     private Date billDueDate;
     private BigDecimal payTotalnet;
     private BigDecimal recTotalnet;
     private BigDecimal payFinalamount;
     private BigDecimal recFinalamount;
     private BigDecimal payPendingamount;
     private BigDecimal recPendingamount;
     private Date crDrDate;
     private BigDecimal crAmount;
     private BigDecimal crSettledAmount;
     private BigDecimal crAvailable;
     private BigDecimal drAmount;
     private BigDecimal drSettledAmount;
     private BigDecimal outstandingAmount;
     private String remarks;
     private BigDecimal weekId;

    public ReconciliationCorp() {
    }

	
    public ReconciliationCorp(BigDecimal slno) {
        this.slno = slno;
    }
    public ReconciliationCorp(BigDecimal slno, Corporates corporates, Date billEntryDate, Date entryDate, String billType, Date billingDate, BigDecimal revisionNo, BigDecimal billYear, Date billDueDate, BigDecimal payTotalnet, BigDecimal recTotalnet, BigDecimal payFinalamount, BigDecimal recFinalamount, BigDecimal payPendingamount, BigDecimal recPendingamount, Date crDrDate, BigDecimal crAmount, BigDecimal crSettledAmount, BigDecimal crAvailable, BigDecimal drAmount, BigDecimal drSettledAmount, BigDecimal outstandingAmount, String remarks, BigDecimal weekId) {
       this.slno = slno;
       this.corporates = corporates;
       this.billEntryDate = billEntryDate;
       this.entryDate = entryDate;
       this.billType = billType;
       this.billingDate = billingDate;
       this.revisionNo = revisionNo;
       this.billYear = billYear;
       this.billDueDate = billDueDate;
       this.payTotalnet = payTotalnet;
       this.recTotalnet = recTotalnet;
       this.payFinalamount = payFinalamount;
       this.recFinalamount = recFinalamount;
       this.payPendingamount = payPendingamount;
       this.recPendingamount = recPendingamount;
       this.crDrDate = crDrDate;
       this.crAmount = crAmount;
       this.crSettledAmount = crSettledAmount;
       this.crAvailable = crAvailable;
       this.drAmount = drAmount;
       this.drSettledAmount = drSettledAmount;
       this.outstandingAmount = outstandingAmount;
       this.remarks = remarks;
       this.weekId = weekId;
    }
   
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }
    public Corporates getCorporates() {
        return this.corporates;
    }
    
    public void setCorporates(Corporates corporates) {
        this.corporates = corporates;
    }
    public Date getBillEntryDate() {
        return this.billEntryDate;
    }
    
    public void setBillEntryDate(Date billEntryDate) {
        this.billEntryDate = billEntryDate;
    }
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
    public String getBillType() {
        return this.billType;
    }
    
    public void setBillType(String billType) {
        this.billType = billType;
    }
    public Date getBillingDate() {
        return this.billingDate;
    }
    
    public void setBillingDate(Date billingDate) {
        this.billingDate = billingDate;
    }
    public BigDecimal getRevisionNo() {
        return this.revisionNo;
    }
    
    public void setRevisionNo(BigDecimal revisionNo) {
        this.revisionNo = revisionNo;
    }
    public BigDecimal getBillYear() {
        return this.billYear;
    }
    
    public void setBillYear(BigDecimal billYear) {
        this.billYear = billYear;
    }
    public Date getBillDueDate() {
        return this.billDueDate;
    }
    
    public void setBillDueDate(Date billDueDate) {
        this.billDueDate = billDueDate;
    }
    public BigDecimal getPayTotalnet() {
        return this.payTotalnet;
    }
    
    public void setPayTotalnet(BigDecimal payTotalnet) {
        this.payTotalnet = payTotalnet;
    }
    public BigDecimal getRecTotalnet() {
        return this.recTotalnet;
    }
    
    public void setRecTotalnet(BigDecimal recTotalnet) {
        this.recTotalnet = recTotalnet;
    }
    public BigDecimal getPayFinalamount() {
        return this.payFinalamount;
    }
    
    public void setPayFinalamount(BigDecimal payFinalamount) {
        this.payFinalamount = payFinalamount;
    }
    public BigDecimal getRecFinalamount() {
        return this.recFinalamount;
    }
    
    public void setRecFinalamount(BigDecimal recFinalamount) {
        this.recFinalamount = recFinalamount;
    }
    public BigDecimal getPayPendingamount() {
        return this.payPendingamount;
    }
    
    public void setPayPendingamount(BigDecimal payPendingamount) {
        this.payPendingamount = payPendingamount;
    }
    public BigDecimal getRecPendingamount() {
        return this.recPendingamount;
    }
    
    public void setRecPendingamount(BigDecimal recPendingamount) {
        this.recPendingamount = recPendingamount;
    }
    public Date getCrDrDate() {
        return this.crDrDate;
    }
    
    public void setCrDrDate(Date crDrDate) {
        this.crDrDate = crDrDate;
    }
    public BigDecimal getCrAmount() {
        return this.crAmount;
    }
    
    public void setCrAmount(BigDecimal crAmount) {
        this.crAmount = crAmount;
    }
    public BigDecimal getCrSettledAmount() {
        return this.crSettledAmount;
    }
    
    public void setCrSettledAmount(BigDecimal crSettledAmount) {
        this.crSettledAmount = crSettledAmount;
    }
    public BigDecimal getCrAvailable() {
        return this.crAvailable;
    }
    
    public void setCrAvailable(BigDecimal crAvailable) {
        this.crAvailable = crAvailable;
    }
    public BigDecimal getDrAmount() {
        return this.drAmount;
    }
    
    public void setDrAmount(BigDecimal drAmount) {
        this.drAmount = drAmount;
    }
    public BigDecimal getDrSettledAmount() {
        return this.drSettledAmount;
    }
    
    public void setDrSettledAmount(BigDecimal drSettledAmount) {
        this.drSettledAmount = drSettledAmount;
    }
    public BigDecimal getOutstandingAmount() {
        return this.outstandingAmount;
    }
    
    public void setOutstandingAmount(BigDecimal outstandingAmount) {
        this.outstandingAmount = outstandingAmount;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public BigDecimal getWeekId() {
        return this.weekId;
    }
    
    public void setWeekId(BigDecimal weekId) {
        this.weekId = weekId;
    }




}


