package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * RevertTempDisbInterest generated by hbm2java
 */
public class RevertTempDisbInterest  implements java.io.Serializable {


     private BigDecimal slno;
     private TempDisbInterestDetails tempDisbInterestDetails;
     private Date entryDate;
     private String checkerStatus;
     private String remarks;

    public RevertTempDisbInterest() {
    }

	
    public RevertTempDisbInterest(BigDecimal slno) {
        this.slno = slno;
    }
    public RevertTempDisbInterest(BigDecimal slno, TempDisbInterestDetails tempDisbInterestDetails, Date entryDate, String checkerStatus, String remarks) {
       this.slno = slno;
       this.tempDisbInterestDetails = tempDisbInterestDetails;
       this.entryDate = entryDate;
       this.checkerStatus = checkerStatus;
       this.remarks = remarks;
    }
   
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }
    public TempDisbInterestDetails getTempDisbInterestDetails() {
        return this.tempDisbInterestDetails;
    }
    
    public void setTempDisbInterestDetails(TempDisbInterestDetails tempDisbInterestDetails) {
        this.tempDisbInterestDetails = tempDisbInterestDetails;
    }
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
    public String getCheckerStatus() {
        return this.checkerStatus;
    }
    
    public void setCheckerStatus(String checkerStatus) {
        this.checkerStatus = checkerStatus;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


