package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * RevertTempInterestDetails generated by hbm2java
 */
public class RevertTempInterestDetails  implements java.io.Serializable {


     private BigDecimal slno;
     private TempInterestDetails tempInterestDetails;
     private Date entryDate;
     private String checkerStatus;
     private String remarks;

    public RevertTempInterestDetails() {
    }

	
    public RevertTempInterestDetails(BigDecimal slno) {
        this.slno = slno;
    }
    public RevertTempInterestDetails(BigDecimal slno, TempInterestDetails tempInterestDetails, Date entryDate, String checkerStatus, String remarks) {
       this.slno = slno;
       this.tempInterestDetails = tempInterestDetails;
       this.entryDate = entryDate;
       this.checkerStatus = checkerStatus;
       this.remarks = remarks;
    }
   
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }
    public TempInterestDetails getTempInterestDetails() {
        return this.tempInterestDetails;
    }
    
    public void setTempInterestDetails(TempInterestDetails tempInterestDetails) {
        this.tempInterestDetails = tempInterestDetails;
    }
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
    public String getCheckerStatus() {
        return this.checkerStatus;
    }
    
    public void setCheckerStatus(String checkerStatus) {
        this.checkerStatus = checkerStatus;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


