package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private BigDecimal slno;
     private String status;

    public Status() {
    }

	
    public Status(BigDecimal slno) {
        this.slno = slno;
    }
    public Status(BigDecimal slno, String status) {
       this.slno = slno;
       this.status = status;
    }
   
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


