package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1



/**
 * State generated by hbm2java
 */
public class State  implements java.io.Serializable {


     private long stateId;
     private String stateName;

    public State() {
    }

    public State(long stateId, String stateName) {
       this.stateId = stateId;
       this.stateName = stateName;
    }
   
    public long getStateId() {
        return this.stateId;
    }
    
    public void setStateId(long stateId) {
        this.stateId = stateId;
    }
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }




}


