package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TempMapBankStatement generated by hbm2java
 */
public class TempMapBankStatement  implements java.io.Serializable {


     private BigDecimal tempStmtid;
     private BankStatement bankStatement;
     private BigDecimal transactionAmount;
     private BigDecimal mappedAmount;
     private BigDecimal transactionBalance;
     private String remarks;
     private BigDecimal corporateId;
     private String checkerStatus;
     private String billCategory;

    public TempMapBankStatement() {
    }

	
    public TempMapBankStatement(BigDecimal tempStmtid) {
        this.tempStmtid = tempStmtid;
    }
    public TempMapBankStatement(BigDecimal tempStmtid, BankStatement bankStatement, BigDecimal transactionAmount, BigDecimal mappedAmount, BigDecimal transactionBalance, String remarks, BigDecimal corporateId, String checkerStatus, String billCategory) {
       this.tempStmtid = tempStmtid;
       this.bankStatement = bankStatement;
       this.transactionAmount = transactionAmount;
       this.mappedAmount = mappedAmount;
       this.transactionBalance = transactionBalance;
       this.remarks = remarks;
       this.corporateId = corporateId;
       this.checkerStatus = checkerStatus;
       this.billCategory = billCategory;
    }
   
    public BigDecimal getTempStmtid() {
        return this.tempStmtid;
    }
    
    public void setTempStmtid(BigDecimal tempStmtid) {
        this.tempStmtid = tempStmtid;
    }
    public BankStatement getBankStatement() {
        return this.bankStatement;
    }
    
    public void setBankStatement(BankStatement bankStatement) {
        this.bankStatement = bankStatement;
    }
    public BigDecimal getTransactionAmount() {
        return this.transactionAmount;
    }
    
    public void setTransactionAmount(BigDecimal transactionAmount) {
        this.transactionAmount = transactionAmount;
    }
    public BigDecimal getMappedAmount() {
        return this.mappedAmount;
    }
    
    public void setMappedAmount(BigDecimal mappedAmount) {
        this.mappedAmount = mappedAmount;
    }
    public BigDecimal getTransactionBalance() {
        return this.transactionBalance;
    }
    
    public void setTransactionBalance(BigDecimal transactionBalance) {
        this.transactionBalance = transactionBalance;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public BigDecimal getCorporateId() {
        return this.corporateId;
    }
    
    public void setCorporateId(BigDecimal corporateId) {
        this.corporateId = corporateId;
    }
    public String getCheckerStatus() {
        return this.checkerStatus;
    }
    
    public void setCheckerStatus(String checkerStatus) {
        this.checkerStatus = checkerStatus;
    }
    public String getBillCategory() {
        return this.billCategory;
    }
    
    public void setBillCategory(String billCategory) {
        this.billCategory = billCategory;
    }




}


