package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TempBillPayableEntityRras generated by hbm2java
 */
public class TempBillPayableEntityRras  implements java.io.Serializable {


     private BigDecimal uniqueId;
     private Corporates corporates;
     private Entites entites;
     private BigDecimal weekId;
     private BigDecimal energyVae;
     private BigDecimal variableCharges;
     private BigDecimal netRras;
     private BigDecimal billYear;
     private BigDecimal revisionNo;
     private String remarks;
     private BigDecimal wrNetRras;
     private String billStatus;
     private BigDecimal prevWrNetRras;

    public TempBillPayableEntityRras() {
    }

	
    public TempBillPayableEntityRras(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }
    public TempBillPayableEntityRras(BigDecimal uniqueId, Corporates corporates, Entites entites, BigDecimal weekId, BigDecimal energyVae, BigDecimal variableCharges, BigDecimal netRras, BigDecimal billYear, BigDecimal revisionNo, String remarks, BigDecimal wrNetRras, String billStatus, BigDecimal prevWrNetRras) {
       this.uniqueId = uniqueId;
       this.corporates = corporates;
       this.entites = entites;
       this.weekId = weekId;
       this.energyVae = energyVae;
       this.variableCharges = variableCharges;
       this.netRras = netRras;
       this.billYear = billYear;
       this.revisionNo = revisionNo;
       this.remarks = remarks;
       this.wrNetRras = wrNetRras;
       this.billStatus = billStatus;
       this.prevWrNetRras = prevWrNetRras;
    }
   
    public BigDecimal getUniqueId() {
        return this.uniqueId;
    }
    
    public void setUniqueId(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }
    public Corporates getCorporates() {
        return this.corporates;
    }
    
    public void setCorporates(Corporates corporates) {
        this.corporates = corporates;
    }
    public Entites getEntites() {
        return this.entites;
    }
    
    public void setEntites(Entites entites) {
        this.entites = entites;
    }
    public BigDecimal getWeekId() {
        return this.weekId;
    }
    
    public void setWeekId(BigDecimal weekId) {
        this.weekId = weekId;
    }
    public BigDecimal getEnergyVae() {
        return this.energyVae;
    }
    
    public void setEnergyVae(BigDecimal energyVae) {
        this.energyVae = energyVae;
    }
    public BigDecimal getVariableCharges() {
        return this.variableCharges;
    }
    
    public void setVariableCharges(BigDecimal variableCharges) {
        this.variableCharges = variableCharges;
    }
    public BigDecimal getNetRras() {
        return this.netRras;
    }
    
    public void setNetRras(BigDecimal netRras) {
        this.netRras = netRras;
    }
    public BigDecimal getBillYear() {
        return this.billYear;
    }
    
    public void setBillYear(BigDecimal billYear) {
        this.billYear = billYear;
    }
    public BigDecimal getRevisionNo() {
        return this.revisionNo;
    }
    
    public void setRevisionNo(BigDecimal revisionNo) {
        this.revisionNo = revisionNo;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public BigDecimal getWrNetRras() {
        return this.wrNetRras;
    }
    
    public void setWrNetRras(BigDecimal wrNetRras) {
        this.wrNetRras = wrNetRras;
    }
    public String getBillStatus() {
        return this.billStatus;
    }
    
    public void setBillStatus(String billStatus) {
        this.billStatus = billStatus;
    }
    public BigDecimal getPrevWrNetRras() {
        return this.prevWrNetRras;
    }
    
    public void setPrevWrNetRras(BigDecimal prevWrNetRras) {
        this.prevWrNetRras = prevWrNetRras;
    }




}


