package sampada.pojo;
// Generated Aug 14, 2023 5:17:36 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TempBillEntitySras generated by hbm2java
 */
public class TempBillEntitySras  implements java.io.Serializable {


     private BigDecimal uniqueId;
     private BigDecimal weekId;
     private Corporates corporates;
     private Entites entites;
     private BigDecimal totalAgcUpdownMwh;
     private BigDecimal totalAgcDownMwh;
     private BigDecimal markupCharges;
     private BigDecimal totalnetAgc;
     private BigDecimal agcEnergycharges;
     private BigDecimal totalcharges;
     private String payRecvflag;
     private BigDecimal billYear;
     private BigDecimal revisionNo;
     private String remarks;
     private BigDecimal wrTotalcharges;
     private String billStatus;
     private BigDecimal prevWrTotalcharges;

    public TempBillEntitySras() {
    }

	
    public TempBillEntitySras(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }
    public TempBillEntitySras(BigDecimal uniqueId, BigDecimal weekId,Corporates corporates, Entites entites, BigDecimal totalAgcUpdownMwh, BigDecimal totalAgcDownMwh, BigDecimal markupCharges, BigDecimal totalnetAgc, BigDecimal agcEnergycharges, BigDecimal totalcharges, String payRecvflag, BigDecimal billYear, BigDecimal revisionNo, String remarks, BigDecimal wrTotalcharges, String billStatus, BigDecimal prevWrTotalcharges) {
       this.uniqueId = uniqueId;
       this.weekId = weekId;
       this.entites = entites;
       this.corporates = corporates;
       this.totalAgcUpdownMwh = totalAgcUpdownMwh;
       this.totalAgcDownMwh = totalAgcDownMwh;
       this.markupCharges = markupCharges;
       this.totalnetAgc = totalnetAgc;
       this.agcEnergycharges = agcEnergycharges;
       this.totalcharges = totalcharges;
       this.payRecvflag = payRecvflag;
       this.billYear = billYear;
       this.revisionNo = revisionNo;
       this.remarks = remarks;
       this.wrTotalcharges = wrTotalcharges;
       this.billStatus = billStatus;
       this.prevWrTotalcharges = prevWrTotalcharges;
    }
   
    public BigDecimal getUniqueId() {
        return this.uniqueId;
    }
    
    public void setUniqueId(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }
    public BigDecimal getWeekId() {
        return this.weekId;
    }
    
    public void setWeekId(BigDecimal weekId) {
        this.weekId = weekId;
    }

    public Corporates getCorporates() {
        return corporates;
    }

    public void setCorporates(Corporates corporates) {
        this.corporates = corporates;
    }

    public Entites getEntites() {
        return entites;
    }

    public void setEntites(Entites entites) {
        this.entites = entites;
    }
   
    public BigDecimal getTotalAgcUpdownMwh() {
        return this.totalAgcUpdownMwh;
    }
    
    public void setTotalAgcUpdownMwh(BigDecimal totalAgcUpdownMwh) {
        this.totalAgcUpdownMwh = totalAgcUpdownMwh;
    }
    public BigDecimal getTotalAgcDownMwh() {
        return this.totalAgcDownMwh;
    }
    
    public void setTotalAgcDownMwh(BigDecimal totalAgcDownMwh) {
        this.totalAgcDownMwh = totalAgcDownMwh;
    }
    public BigDecimal getMarkupCharges() {
        return this.markupCharges;
    }
    
    public void setMarkupCharges(BigDecimal markupCharges) {
        this.markupCharges = markupCharges;
    }
    public BigDecimal getTotalnetAgc() {
        return this.totalnetAgc;
    }
    
    public void setTotalnetAgc(BigDecimal totalnetAgc) {
        this.totalnetAgc = totalnetAgc;
    }
    public BigDecimal getAgcEnergycharges() {
        return this.agcEnergycharges;
    }
    
    public void setAgcEnergycharges(BigDecimal agcEnergycharges) {
        this.agcEnergycharges = agcEnergycharges;
    }
    public BigDecimal getTotalcharges() {
        return this.totalcharges;
    }
    
    public void setTotalcharges(BigDecimal totalcharges) {
        this.totalcharges = totalcharges;
    }
    public String getPayRecvflag() {
        return this.payRecvflag;
    }
    
    public void setPayRecvflag(String payRecvflag) {
        this.payRecvflag = payRecvflag;
    }
    public BigDecimal getBillYear() {
        return this.billYear;
    }
    
    public void setBillYear(BigDecimal billYear) {
        this.billYear = billYear;
    }
    public BigDecimal getRevisionNo() {
        return this.revisionNo;
    }
    
    public void setRevisionNo(BigDecimal revisionNo) {
        this.revisionNo = revisionNo;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public BigDecimal getWrTotalcharges() {
        return this.wrTotalcharges;
    }
    
    public void setWrTotalcharges(BigDecimal wrTotalcharges) {
        this.wrTotalcharges = wrTotalcharges;
    }
    public String getBillStatus() {
        return this.billStatus;
    }
    
    public void setBillStatus(String billStatus) {
        this.billStatus = billStatus;
    }
    public BigDecimal getPrevWrTotalcharges() {
        return this.prevWrTotalcharges;
    }
    
    public void setPrevWrTotalcharges(BigDecimal prevWrTotalcharges) {
        this.prevWrTotalcharges = prevWrTotalcharges;
    }




}


