package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TempBillEntityFras generated by hbm2java
 */
public class TempBillEntityFras  implements java.io.Serializable {


     private BigDecimal uniqueId;
     private Corporates corporates;
     private Entites entites;
     private BigDecimal weekId;
     private BigDecimal upRegulation;
     private BigDecimal downRegulation;
     private BigDecimal markupCharges;
     private BigDecimal wrMarkupCharges;
     private BigDecimal billYear;
     private BigDecimal revisionNo;
     private String remarks;
     private String billStatus;
     private BigDecimal prevWrMarkupCharges;

    public TempBillEntityFras() {
    }

	
    public TempBillEntityFras(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }
    public TempBillEntityFras(BigDecimal uniqueId, Corporates corporates, Entites entites, BigDecimal weekId, BigDecimal upRegulation, BigDecimal downRegulation, BigDecimal markupCharges, BigDecimal wrMarkupCharges, BigDecimal billYear, BigDecimal revisionNo, String remarks, String billStatus, BigDecimal prevWrMarkupCharges) {
       this.uniqueId = uniqueId;
       this.corporates = corporates;
       this.entites = entites;
       this.weekId = weekId;
       this.upRegulation = upRegulation;
       this.downRegulation = downRegulation;
       this.markupCharges = markupCharges;
       this.wrMarkupCharges = wrMarkupCharges;
       this.billYear = billYear;
       this.revisionNo = revisionNo;
       this.remarks = remarks;
       this.billStatus = billStatus;
       this.prevWrMarkupCharges = prevWrMarkupCharges;
    }
   
    public BigDecimal getUniqueId() {
        return this.uniqueId;
    }
    
    public void setUniqueId(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }
    public Corporates getCorporates() {
        return this.corporates;
    }
    
    public void setCorporates(Corporates corporates) {
        this.corporates = corporates;
    }
    public Entites getEntites() {
        return this.entites;
    }
    
    public void setEntites(Entites entites) {
        this.entites = entites;
    }
    public BigDecimal getWeekId() {
        return this.weekId;
    }
    
    public void setWeekId(BigDecimal weekId) {
        this.weekId = weekId;
    }
    public BigDecimal getUpRegulation() {
        return this.upRegulation;
    }
    
    public void setUpRegulation(BigDecimal upRegulation) {
        this.upRegulation = upRegulation;
    }
    public BigDecimal getDownRegulation() {
        return this.downRegulation;
    }
    
    public void setDownRegulation(BigDecimal downRegulation) {
        this.downRegulation = downRegulation;
    }
    public BigDecimal getMarkupCharges() {
        return this.markupCharges;
    }
    
    public void setMarkupCharges(BigDecimal markupCharges) {
        this.markupCharges = markupCharges;
    }
    public BigDecimal getWrMarkupCharges() {
        return this.wrMarkupCharges;
    }
    
    public void setWrMarkupCharges(BigDecimal wrMarkupCharges) {
        this.wrMarkupCharges = wrMarkupCharges;
    }
    public BigDecimal getBillYear() {
        return this.billYear;
    }
    
    public void setBillYear(BigDecimal billYear) {
        this.billYear = billYear;
    }
    public BigDecimal getRevisionNo() {
        return this.revisionNo;
    }
    
    public void setRevisionNo(BigDecimal revisionNo) {
        this.revisionNo = revisionNo;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getBillStatus() {
        return this.billStatus;
    }
    
    public void setBillStatus(String billStatus) {
        this.billStatus = billStatus;
    }
    public BigDecimal getPrevWrMarkupCharges() {
        return this.prevWrMarkupCharges;
    }
    
    public void setPrevWrMarkupCharges(BigDecimal prevWrMarkupCharges) {
        this.prevWrMarkupCharges = prevWrMarkupCharges;
    }




}


