package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TempBillPayableCorp generated by hbm2java
 */
public class TempBillPayableCorp  implements java.io.Serializable {


     private BigDecimal uniqueId;
     private Corporates corporates;
     private BigDecimal weekId;
     private BigDecimal totalnet;
     private Date billingDate;
     private BigDecimal billYear;
     private BigDecimal revisionNo;
     private String remarks;
     private String billType;
     private String billStatus;

    public TempBillPayableCorp() {
    }

	
    public TempBillPayableCorp(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }
    public TempBillPayableCorp(BigDecimal uniqueId, Corporates corporates, BigDecimal weekId, BigDecimal totalnet, Date billingDate, BigDecimal billYear, BigDecimal revisionNo, String remarks, String billType, String billStatus) {
       this.uniqueId = uniqueId;
       this.corporates = corporates;
       this.weekId = weekId;
       this.totalnet = totalnet;
       this.billingDate = billingDate;
       this.billYear = billYear;
       this.revisionNo = revisionNo;
       this.remarks = remarks;
       this.billType = billType;
       this.billStatus = billStatus;
    }
   
    public BigDecimal getUniqueId() {
        return this.uniqueId;
    }
    
    public void setUniqueId(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }
    public Corporates getCorporates() {
        return this.corporates;
    }
    
    public void setCorporates(Corporates corporates) {
        this.corporates = corporates;
    }
    public BigDecimal getWeekId() {
        return this.weekId;
    }
    
    public void setWeekId(BigDecimal weekId) {
        this.weekId = weekId;
    }
    public BigDecimal getTotalnet() {
        return this.totalnet;
    }
    
    public void setTotalnet(BigDecimal totalnet) {
        this.totalnet = totalnet;
    }
    public Date getBillingDate() {
        return this.billingDate;
    }
    
    public void setBillingDate(Date billingDate) {
        this.billingDate = billingDate;
    }
    public BigDecimal getBillYear() {
        return this.billYear;
    }
    
    public void setBillYear(BigDecimal billYear) {
        this.billYear = billYear;
    }
    public BigDecimal getRevisionNo() {
        return this.revisionNo;
    }
    
    public void setRevisionNo(BigDecimal revisionNo) {
        this.revisionNo = revisionNo;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getBillType() {
        return this.billType;
    }
    
    public void setBillType(String billType) {
        this.billType = billType;
    }
    public String getBillStatus() {
        return this.billStatus;
    }
    
    public void setBillStatus(String billStatus) {
        this.billStatus = billStatus;
    }




}


