package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TempPaymentDisbursement generated by hbm2java
 */
public class TempPaymentDisbursement implements java.io.Serializable {

    private BigDecimal disburseId;
    private Corporates corporates;
    private BillReceiveCorp billReceiveCorp;
    private BigDecimal weekId;
    private Date billingDate;
    private BigDecimal disburseAmount;
    private String disburseCategory;
    private String disburseStatus;
    private Date disbursalDate;
    private BigDecimal disburseYear;
    private BigDecimal adjustedAmount;
    private String remarks;
    private Date entryDate;
    private String checkerStatus;
    private BigDecimal totalAmount;
    private String billType;
    private BigDecimal pendingAmount;
    private Date billDueDate;
    private BigDecimal poolBal;
    private BigDecimal poolAgcBal;
    private BigDecimal poolRrasBal;
    private Date entryTime;

    public TempPaymentDisbursement() {
    }

    public TempPaymentDisbursement(BigDecimal disburseId) {
        this.disburseId = disburseId;
    }

    public TempPaymentDisbursement(BigDecimal disburseId, Corporates corporates, BillReceiveCorp billReceiveCorp, BigDecimal weekId, Date billingDate, BigDecimal disburseAmount, String disburseCategory, String disburseStatus, Date disbursalDate, BigDecimal disburseYear, BigDecimal adjustedAmount, String remarks, Date entryDate, String checkerStatus, BigDecimal totalAmount, String billType, BigDecimal pendingAmount, Date billDueDate, BigDecimal poolBal, BigDecimal poolAgcBal, BigDecimal poolRrasBal, Date entryTime) {
        this.disburseId = disburseId;
        this.corporates = corporates;
        this.billReceiveCorp = billReceiveCorp;
        this.weekId = weekId;
        this.billingDate = billingDate;
        this.disburseAmount = disburseAmount;
        this.disburseCategory = disburseCategory;
        this.disburseStatus = disburseStatus;
        this.disbursalDate = disbursalDate;
        this.disburseYear = disburseYear;
        this.adjustedAmount = adjustedAmount;
        this.remarks = remarks;
        this.entryDate = entryDate;
        this.checkerStatus = checkerStatus;
        this.totalAmount = totalAmount;
        this.billType = billType;
        this.pendingAmount = pendingAmount;
        this.billDueDate = billDueDate;
        this.poolBal = poolBal;
        this.poolAgcBal = poolAgcBal;
        this.poolRrasBal = poolRrasBal;
        this.entryTime = entryTime;
    }

    public BigDecimal getDisburseId() {
        return this.disburseId;
    }

    public void setDisburseId(BigDecimal disburseId) {
        this.disburseId = disburseId;
    }

    public Corporates getCorporates() {
        return this.corporates;
    }

    public void setCorporates(Corporates corporates) {
        this.corporates = corporates;
    }

    public BillReceiveCorp getBillReceiveCorp() {
        return this.billReceiveCorp;
    }

    public void setBillReceiveCorp(BillReceiveCorp billReceiveCorp) {
        this.billReceiveCorp = billReceiveCorp;
    }

    public BigDecimal getWeekId() {
        return this.weekId;
    }

    public void setWeekId(BigDecimal weekId) {
        this.weekId = weekId;
    }

    public Date getBillingDate() {
        return this.billingDate;
    }

    public void setBillingDate(Date billingDate) {
        this.billingDate = billingDate;
    }

    public BigDecimal getDisburseAmount() {
        return this.disburseAmount;
    }

    public void setDisburseAmount(BigDecimal disburseAmount) {
        this.disburseAmount = disburseAmount;
    }

    public String getDisburseCategory() {
        return this.disburseCategory;
    }

    public void setDisburseCategory(String disburseCategory) {
        this.disburseCategory = disburseCategory;
    }

    public String getDisburseStatus() {
        return this.disburseStatus;
    }

    public void setDisburseStatus(String disburseStatus) {
        this.disburseStatus = disburseStatus;
    }

    public Date getDisbursalDate() {
        return this.disbursalDate;
    }

    public void setDisbursalDate(Date disbursalDate) {
        this.disbursalDate = disbursalDate;
    }

    public BigDecimal getDisburseYear() {
        return this.disburseYear;
    }

    public void setDisburseYear(BigDecimal disburseYear) {
        this.disburseYear = disburseYear;
    }

    public BigDecimal getAdjustedAmount() {
        return this.adjustedAmount;
    }

    public void setAdjustedAmount(BigDecimal adjustedAmount) {
        this.adjustedAmount = adjustedAmount;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Date getEntryDate() {
        return this.entryDate;
    }

    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    public String getCheckerStatus() {
        return this.checkerStatus;
    }

    public void setCheckerStatus(String checkerStatus) {
        this.checkerStatus = checkerStatus;
    }

    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public String getBillType() {
        return this.billType;
    }

    public void setBillType(String billType) {
        this.billType = billType;
    }

    public BigDecimal getPendingAmount() {
        return this.pendingAmount;
    }

    public void setPendingAmount(BigDecimal pendingAmount) {
        this.pendingAmount = pendingAmount;
    }

    public Date getBillDueDate() {
        return this.billDueDate;
    }

    public void setBillDueDate(Date billDueDate) {
        this.billDueDate = billDueDate;
    }

    public BigDecimal getPoolBal() {
        return this.poolBal;
    }

    public void setPoolBal(BigDecimal poolBal) {
        this.poolBal = poolBal;
    }

    public BigDecimal getPoolAgcBal() {
        return poolAgcBal;
    }

    public void setPoolAgcBal(BigDecimal poolAgcBal) {
        this.poolAgcBal = poolAgcBal;
    }

    public BigDecimal getPoolRrasBal() {
        return poolRrasBal;
    }

    public void setPoolRrasBal(BigDecimal poolRrasBal) {
        this.poolRrasBal = poolRrasBal;
    }

    public Date getEntryTime() {
        return entryTime;
    }

    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    
    
}
