package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TempRefundBillCorp generated by hbm2java
 */
public class TempRefundBillCorp  implements java.io.Serializable {


     private BigDecimal slno;
     private Corporates corporates;
     private UserDetails userDetails;
     private BillReceiveCorp billReceiveCorp;
     private BillPayableCorp billPayableCorp;
     private BigDecimal weekid;
     private Date refundDate;
     private BigDecimal totalAmount;
     private String checkerStatus;
     private Date checkerDate;
     private BigDecimal paidAmount;
     private BigDecimal pendingAmount;
     private String remarks;
     private BigDecimal poolBal;
     private Date entryTime;
           private BigDecimal poolAgcBal;
    private BigDecimal poolRrasBal;
     private Set mappingRefundBanks = new HashSet(0);

    public TempRefundBillCorp() {
    }

	
    public TempRefundBillCorp(BigDecimal slno) {
        this.slno = slno;
    }
    public TempRefundBillCorp(BigDecimal slno, Corporates corporates, UserDetails userDetails, BillReceiveCorp billReceiveCorp, BillPayableCorp billPayableCorp, BigDecimal weekid, Date refundDate, BigDecimal totalAmount, String checkerStatus, Date checkerDate, BigDecimal paidAmount, BigDecimal pendingAmount, String remarks, BigDecimal poolBal, Date entryTime, BigDecimal poolAgcBal, BigDecimal poolRrasBal, Set mappingRefundBanks) {
       this.slno = slno;
       this.corporates = corporates;
       this.userDetails = userDetails;
       this.billReceiveCorp = billReceiveCorp;
       this.billPayableCorp = billPayableCorp;
       this.weekid = weekid;
       this.refundDate = refundDate;
       this.totalAmount = totalAmount;
       this.checkerStatus = checkerStatus;
       this.checkerDate = checkerDate;
       this.paidAmount = paidAmount;
       this.pendingAmount = pendingAmount;
       this.remarks = remarks;
       this.poolBal = poolBal;
       this.entryTime = entryTime;
         this.poolAgcBal = poolAgcBal;
        this.poolRrasBal = poolRrasBal;
       this.mappingRefundBanks = mappingRefundBanks;
    }
   
    public BigDecimal getSlno() {
        return this.slno;
    }
    
    public void setSlno(BigDecimal slno) {
        this.slno = slno;
    }
    public Corporates getCorporates() {
        return this.corporates;
    }
    
    public void setCorporates(Corporates corporates) {
        this.corporates = corporates;
    }
    public UserDetails getUserDetails() {
        return this.userDetails;
    }
    
    public void setUserDetails(UserDetails userDetails) {
        this.userDetails = userDetails;
    }
    public BillReceiveCorp getBillReceiveCorp() {
        return this.billReceiveCorp;
    }
    
    public void setBillReceiveCorp(BillReceiveCorp billReceiveCorp) {
        this.billReceiveCorp = billReceiveCorp;
    }
    public BillPayableCorp getBillPayableCorp() {
        return this.billPayableCorp;
    }
    
    public void setBillPayableCorp(BillPayableCorp billPayableCorp) {
        this.billPayableCorp = billPayableCorp;
    }
    public BigDecimal getWeekid() {
        return this.weekid;
    }
    
    public void setWeekid(BigDecimal weekid) {
        this.weekid = weekid;
    }
    public Date getRefundDate() {
        return this.refundDate;
    }
    
    public void setRefundDate(Date refundDate) {
        this.refundDate = refundDate;
    }
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }
    public String getCheckerStatus() {
        return this.checkerStatus;
    }
    
    public void setCheckerStatus(String checkerStatus) {
        this.checkerStatus = checkerStatus;
    }
    public Date getCheckerDate() {
        return this.checkerDate;
    }
    
    public void setCheckerDate(Date checkerDate) {
        this.checkerDate = checkerDate;
    }
    public BigDecimal getPaidAmount() {
        return this.paidAmount;
    }
    
    public void setPaidAmount(BigDecimal paidAmount) {
        this.paidAmount = paidAmount;
    }
    public BigDecimal getPendingAmount() {
        return this.pendingAmount;
    }
    
    public void setPendingAmount(BigDecimal pendingAmount) {
        this.pendingAmount = pendingAmount;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public BigDecimal getPoolBal() {
        return this.poolBal;
    }
    
    public void setPoolBal(BigDecimal poolBal) {
        this.poolBal = poolBal;
    }
    public Date getEntryTime() {
        return this.entryTime;
    }
    
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    public BigDecimal getPoolAgcBal() {
        return poolAgcBal;
    }

    public void setPoolAgcBal(BigDecimal poolAgcBal) {
        this.poolAgcBal = poolAgcBal;
    }

    public BigDecimal getPoolRrasBal() {
        return poolRrasBal;
    }

    public void setPoolRrasBal(BigDecimal poolRrasBal) {
        this.poolRrasBal = poolRrasBal;
    }
    
    public Set getMappingRefundBanks() {
        return this.mappingRefundBanks;
    }
    
    public void setMappingRefundBanks(Set mappingRefundBanks) {
        this.mappingRefundBanks = mappingRefundBanks;
    }




}


