package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TempBillEntityAgc generated by hbm2java
 */
public class TempBillEntityAgc  implements java.io.Serializable {


     private BigDecimal uniqueId;
     private Corporates corporates;
     private Entites entites;
     private BigDecimal weekId;
     private BigDecimal totalAgcUpdownMwh;
     private BigDecimal markupCharges;
     private BigDecimal totalnetAgc;
     private BigDecimal agcEnergycharges;
     private BigDecimal totalcharges;
     private String payRecvflag;
     private BigDecimal billYear;
     private BigDecimal revisionNo;
     private String remarks;
     private BigDecimal wrTotalcharges;
     private String billStatus;
     private BigDecimal prevWrTotalcharges;

    public TempBillEntityAgc() {
    }

	
    public TempBillEntityAgc(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }
    public TempBillEntityAgc(BigDecimal uniqueId, Corporates corporates, Entites entites, BigDecimal weekId, BigDecimal totalAgcUpdownMwh, BigDecimal markupCharges, BigDecimal totalnetAgc, BigDecimal agcEnergycharges, BigDecimal totalcharges, String payRecvflag, BigDecimal billYear, BigDecimal revisionNo, String remarks, BigDecimal wrTotalcharges, String billStatus, BigDecimal prevWrTotalcharges) {
       this.uniqueId = uniqueId;
       this.corporates = corporates;
       this.entites = entites;
       this.weekId = weekId;
       this.totalAgcUpdownMwh = totalAgcUpdownMwh;
       this.markupCharges = markupCharges;
       this.totalnetAgc = totalnetAgc;
       this.agcEnergycharges = agcEnergycharges;
       this.totalcharges = totalcharges;
       this.payRecvflag = payRecvflag;
       this.billYear = billYear;
       this.revisionNo = revisionNo;
       this.remarks = remarks;
       this.wrTotalcharges = wrTotalcharges;
       this.billStatus = billStatus;
       this.prevWrTotalcharges = prevWrTotalcharges;
    }
   
    public BigDecimal getUniqueId() {
        return this.uniqueId;
    }
    
    public void setUniqueId(BigDecimal uniqueId) {
        this.uniqueId = uniqueId;
    }
    public Corporates getCorporates() {
        return this.corporates;
    }
    
    public void setCorporates(Corporates corporates) {
        this.corporates = corporates;
    }
    public Entites getEntites() {
        return this.entites;
    }
    
    public void setEntites(Entites entites) {
        this.entites = entites;
    }
    public BigDecimal getWeekId() {
        return this.weekId;
    }
    
    public void setWeekId(BigDecimal weekId) {
        this.weekId = weekId;
    }
    public BigDecimal getTotalAgcUpdownMwh() {
        return this.totalAgcUpdownMwh;
    }
    
    public void setTotalAgcUpdownMwh(BigDecimal totalAgcUpdownMwh) {
        this.totalAgcUpdownMwh = totalAgcUpdownMwh;
    }
    public BigDecimal getMarkupCharges() {
        return this.markupCharges;
    }
    
    public void setMarkupCharges(BigDecimal markupCharges) {
        this.markupCharges = markupCharges;
    }
    public BigDecimal getTotalnetAgc() {
        return this.totalnetAgc;
    }
    
    public void setTotalnetAgc(BigDecimal totalnetAgc) {
        this.totalnetAgc = totalnetAgc;
    }
    public BigDecimal getAgcEnergycharges() {
        return this.agcEnergycharges;
    }
    
    public void setAgcEnergycharges(BigDecimal agcEnergycharges) {
        this.agcEnergycharges = agcEnergycharges;
    }
    public BigDecimal getTotalcharges() {
        return this.totalcharges;
    }
    
    public void setTotalcharges(BigDecimal totalcharges) {
        this.totalcharges = totalcharges;
    }
    public String getPayRecvflag() {
        return this.payRecvflag;
    }
    
    public void setPayRecvflag(String payRecvflag) {
        this.payRecvflag = payRecvflag;
    }
    public BigDecimal getBillYear() {
        return this.billYear;
    }
    
    public void setBillYear(BigDecimal billYear) {
        this.billYear = billYear;
    }
    public BigDecimal getRevisionNo() {
        return this.revisionNo;
    }
    
    public void setRevisionNo(BigDecimal revisionNo) {
        this.revisionNo = revisionNo;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public BigDecimal getWrTotalcharges() {
        return this.wrTotalcharges;
    }
    
    public void setWrTotalcharges(BigDecimal wrTotalcharges) {
        this.wrTotalcharges = wrTotalcharges;
    }
    public String getBillStatus() {
        return this.billStatus;
    }
    
    public void setBillStatus(String billStatus) {
        this.billStatus = billStatus;
    }
    public BigDecimal getPrevWrTotalcharges() {
        return this.prevWrTotalcharges;
    }
    
    public void setPrevWrTotalcharges(BigDecimal prevWrTotalcharges) {
        this.prevWrTotalcharges = prevWrTotalcharges;
    }




}


