package sampada.pojo;
// Generated Jan 4, 2021 2:25:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserDetails generated by hbm2java
 */
public class UserDetails  implements java.io.Serializable {


     private String loginId;
     private Corporates corporates;
     private String userType;
     private String password;
     private Integer roleId;
     private String name;
     private String sname;
     private String designation;
     private String phoneOffice;
     private String phoneResi;
     private String mobileNo;
     private String emailid;
     private String fax;
     private String address;
     private char validity;
     private char locked;
     private Date entryDate;
     private String remarks;
     private Set tempMappingBillBanks = new HashSet(0);
     private Set bankStatements = new HashSet(0);
     private Set tempRefundBillCorps = new HashSet(0);
     private Set mappingBillBanks = new HashSet(0);

    public UserDetails() {
    }

	
    public UserDetails(String loginId, String userType, String password, String name, char validity, char locked) {
        this.loginId = loginId;
        this.userType = userType;
        this.password = password;
        this.name = name;
        this.validity = validity;
        this.locked = locked;
    }
    public UserDetails(String loginId, Corporates corporates, String userType, String password, Integer roleId, String name, String sname, String designation, String phoneOffice, String phoneResi, String mobileNo, String emailid, String fax, String address, char validity, char locked, Date entryDate, String remarks, Set tempMappingBillBanks, Set bankStatements, Set tempRefundBillCorps, Set mappingBillBanks) {
       this.loginId = loginId;
       this.corporates = corporates;
       this.userType = userType;
       this.password = password;
       this.roleId = roleId;
       this.name = name;
       this.sname = sname;
       this.designation = designation;
       this.phoneOffice = phoneOffice;
       this.phoneResi = phoneResi;
       this.mobileNo = mobileNo;
       this.emailid = emailid;
       this.fax = fax;
       this.address = address;
       this.validity = validity;
       this.locked = locked;
       this.entryDate = entryDate;
       this.remarks = remarks;
       this.tempMappingBillBanks = tempMappingBillBanks;
       this.bankStatements = bankStatements;
       this.tempRefundBillCorps = tempRefundBillCorps;
       this.mappingBillBanks = mappingBillBanks;
    }
   
    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }
    public Corporates getCorporates() {
        return this.corporates;
    }
    
    public void setCorporates(Corporates corporates) {
        this.corporates = corporates;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getPhoneOffice() {
        return this.phoneOffice;
    }
    
    public void setPhoneOffice(String phoneOffice) {
        this.phoneOffice = phoneOffice;
    }
    public String getPhoneResi() {
        return this.phoneResi;
    }
    
    public void setPhoneResi(String phoneResi) {
        this.phoneResi = phoneResi;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public char getValidity() {
        return this.validity;
    }
    
    public void setValidity(char validity) {
        this.validity = validity;
    }
    public char getLocked() {
        return this.locked;
    }
    
    public void setLocked(char locked) {
        this.locked = locked;
    }
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Set getTempMappingBillBanks() {
        return this.tempMappingBillBanks;
    }
    
    public void setTempMappingBillBanks(Set tempMappingBillBanks) {
        this.tempMappingBillBanks = tempMappingBillBanks;
    }
    public Set getBankStatements() {
        return this.bankStatements;
    }
    
    public void setBankStatements(Set bankStatements) {
        this.bankStatements = bankStatements;
    }
    public Set getTempRefundBillCorps() {
        return this.tempRefundBillCorps;
    }
    
    public void setTempRefundBillCorps(Set tempRefundBillCorps) {
        this.tempRefundBillCorps = tempRefundBillCorps;
    }
    public Set getMappingBillBanks() {
        return this.mappingBillBanks;
    }
    
    public void setMappingBillBanks(Set mappingBillBanks) {
        this.mappingBillBanks = mappingBillBanks;
    }




}


